// v2.5 native workbench regression suite; models and host are simulated, never external calls.
const {JSDOM}=require('jsdom'),fs=require('fs'),path=require('path'),A=require('node:assert/strict');
let code=fs.readFileSync(process.argv[2]||path.join(__dirname,'..','tsukiyo-phone-2.5.0.js'),'utf8');
code=code.slice(0,code.lastIndexOf('TsukiyoPhoneBundle.start('));
code=code.replace('    VERSION: () => VERSION,','    StudioTest: () => ({studioFresh,studioData,studioRules,studioRulePrompt,studioImportRules,studioPutRule,studioValidate,studioReadEvents,studioSelect,studioStamp,studioValid,studioEligible,studioMemoryFor,studioProjection,studioDirectorOn,studioBasePhone,studioDateValid,studioAction,studioApproveState,avsFresh,fingerprint}),\n    VERSION: () => VERSION,');
const dom=new JSDOM('<!doctype html><html><body></body></html>',{runScripts:'outside-only',pretendToBeVisual:true,url:'https://studio.test/'}),w=dom.window;
w.console=console;w.eval(code+'\nwindow.B=TsukiyoPhoneBundle;');const B=w.B,T=B.StudioTest;
let n=0;const test=(name,f)=>{f();n++;console.log('PASS',name);};const wait=ms=>new Promise(r=>setTimeout(r,ms));
const s={studio:T.studioFresh()},snap={floor:0,lineage:['a'],history:[],present:[]}, stamp=T.studioStamp(snap);
const eventRaw={events:[{title:'便笺',weight:10,secret:'NEVER_SEND_SECRET',stages:[{hook:'CURRENT_HOOK',condition:'NEVER_SEND_CONDITION'},{hook:'NEVER_SEND_FUTURE',condition:'done'}]}]};
const ev=T.studioReadEvents(JSON.stringify(eventRaw),snap)[0];
test('v2.5 and all new injection defaults OFF',()=>{A.equal(B.VERSION,'2.5.0');for(const k of ['directorInject','worldInject','memoryInject'])A.equal(s.studio.config[k],false);});
test('290 built-in rules, 13 compact default workflow topics',()=>{A.equal(T.studioRules(s).length,290);A.equal(T.studioRulePrompt(s).used.length,13);});
test('toggling default workflow does not unexpectedly expand its input',()=>{const copy={studio:T.studioFresh()},r=T.studioRules(copy).find(r=>r.use);const before=T.studioRulePrompt(copy).text;T.studioPutRule(copy,{...r,enabled:false});T.studioPutRule(copy,{...r,enabled:true});A.equal(T.studioRulePrompt(copy).text,before);});
const base=T.studioRules(s)[0];
T.studioPutRule(s,{...base,text:'EDITED_RULE_SENTINEL',use:true,enabled:true});
test('editing a rule changes effective text, never mutates constant library',()=>{A.equal(T.studioRules(s)[0].text,'EDITED_RULE_SENTINEL');A.notEqual(T.studioRules({})[0].text,'EDITED_RULE_SENTINEL');A.match(T.studioRulePrompt(s).text,/EDITED_RULE_SENTINEL/);});
T.studioPutRule(s,{id:'custom-rule',title:'自建',keys:['测试'],text:'CUSTOM_RULE',enabled:true,use:true});
test('new rules participate only when explicitly selected',()=>{A.equal(T.studioRules(s).length,291);A.match(T.studioRulePrompt(s).text,/CUSTOM_RULE/);});
T.studioPutRule(s,{id:'large-rule',title:'过长',keys:[],text:'长'.repeat(10000),enabled:true,use:true});
test('oversized selected rule reported as omitted, no partial instructions',()=>{const p=T.studioRulePrompt(s);A.ok(p.text.length<=6000);A.ok(p.omitted.includes('large-rule'));A.ok(!p.text.includes('长'.repeat(100)));});
test('import/export default roundtrip preserves compact prompts',()=>{const rows=T.studioImportRules({format:'tsukiyo-visual-rules-1',rules:T.studioRules({})});A.equal(rows.length,0);});
test('import/export overrides roundtrip',()=>{const rows=T.studioImportRules({format:'tsukiyo-visual-rules-1',rules:T.studioRules(s)});A.equal(rows.length,3);});
test('malformed, duplicate and prototype imports rejected',()=>{A.throws(()=>T.studioImportRules({format:'wrong',rules:[]}));A.throws(()=>T.studioImportRules({format:'tsukiyo-visual-rules-1',rules:[base,base]}));A.throws(()=>T.studioPutRule(s,{...base,id:'__proto__'}));});
test('legacy v2 save accepts absent studio data',()=>T.studioValidate(undefined));
test('new store validated with bounds',()=>{T.studioValidate(s.studio);A.throws(()=>T.studioValidate({...T.studioFresh(),rules:Array(451).fill(base)}));});
test('event parser requires stages and rejects invalid shape',()=>{A.equal(ev.stages.length,2);A.throws(()=>T.studioReadEvents('{"events":[{"title":"x","stages":[]}]}',snap));});
let st=T.studioFresh();st.pool=[ev];st.config.probability=100;
const roll=T.studioSelect(st,snap,()=>0);
test('weighted draw activates one candidate',()=>{A.equal(roll.eventId,ev.id);A.equal(st.active.index,0);});
st.active=null;
test('same narrative prefix does not reroll after cancellation',()=>A.equal(T.studioSelect(st,snap,()=>0).repeat,true));
st=T.studioFresh();st.pool=[{...ev,status:"candidate"}];st.config.probability=0;
test('zero probability produces a recorded no-event cycle',()=>{A.equal(T.studioSelect(st,snap,()=>0).eventId,'');A.equal(st.cycles.length,1);});
test('edited branch invalidates proposed event source',()=>A.equal(T.studioValid(ev,{...snap,lineage:['changed']}),false));
test('plot clock validation rejects nonexistent dates',()=>{A.equal(T.studioDateValid('1604-09-03T18:00'),true);A.equal(T.studioDateValid('2026-02-30T12:00'),false);});
(async()=>{
 const app=B.start({mode:'demo',source:w});
 try{
  await wait(300);const e=app.engine,u=app.ui;e.scheduler.stop();e.arc.stop();e.memoryBook.stop();clearInterval(e.timer);u.confirm=async()=>true;
  const cap=e.bridge.capture.bind(e.bridge),api=e.router.call.bind(e.router);
  test('three new API routes available',()=>{for(const k of ['director','parallel','world'])A.equal(e.settings.route(k).id,'tavern');});
  e.bridge.chat='demo-new-unrefreshed';
  await A.rejects(e.studio.generate('director'),/正在刷新/);
  test('new generation cannot read stale previous-chat UI data',()=>A.equal(e.repo.data.studio.attempts.length,0));
  await A.rejects(e.visual.sync(),/正在刷新/);
  test('visual sync also rejects unrefreshed cross-chat context',()=>A.equal(e.repo.data.visual.attempts.length,0));
  e.bridge.chat='demo-a';

  u.open('visualRules');
  test('editable library has new/import/export and 12-row pagination',()=>{A.ok(u.shadow.querySelector('[data-action="st-rule-new"]'));A.ok(u.shadow.querySelector('[data-action="st-rule-import"]'));A.equal(u.shadow.querySelectorAll('details.card').length,12);});
  await wait(460);u.shadow.querySelector('[data-action="st-rule-new"]').click();await wait(10);
  const form=u.shadow.querySelector('#modals form');A.ok(form);
  form.querySelector('[name="title"]').value='真实表单测试';form.querySelector('[name="text"]').value='<img src=x onerror=alert(1)>FORM_SAVE';
  form.querySelector('[name="use"]').checked=true;
  form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));await wait(40);
  test('real DOM rule form saves and escapes HTML rather than executing it',()=>{A.ok(T.studioRules(e.repo.data).some(r=>r.title==='真实表单测试'));A.ok(!u.shadow.querySelector('img[src="x"]'));});
  await e.mutate(s=>{s.studio.rules=[];});
  const originalDialog=u.dialog.bind(u);u.dialog=async()=>({title:'本聊天规则',keys:'a,b',text:'NATIVE_EDITOR_SENTINEL',enabled:true,use:true});
  await T.studioAction(u,'st-rule-new','');u.dialog=originalDialog;
  test('editor action persists custom rule to actual phone repository',()=>{A.equal(T.studioRules(e.repo.data).length,291);A.match(T.studioRulePrompt(e.repo.data).text,/NATIVE_EDITOR_SENTINEL/);});
  let visualRequest;
  e.router.call=async(module,req)=>{visualRequest=req;return '{"characters":[]}';};
  await e.visual.sync();
  test('edited rule reaches actual visual generation system prompt',()=>A.match(visualRequest.system,/NATIVE_EDITOR_SENTINEL/));
  e.router.call=api;
  await e.studio.generate('director');
  test('director generation saves candidate, does not activate or inject',()=>{A.equal(e.repo.data.studio.pool.length,1);A.equal(e.repo.data.studio.active,null);A.ok(!e.prompt.includes('当前事件引导'));});
  const event=e.repo.data.studio.pool[0];
  await e.mutate(s=>{s.studio.pool[0].secret='SECRET_NOT_IN_PROMPT';s.studio.pool[0].stages[1].hook='FUTURE_NOT_IN_PROMPT';});
  await T.studioAction(u,'st-event-start',event.id);await T.studioAction(u,'st-toggle','directorInject');
  test('only current stage injected, hidden and future fields excluded',()=>{A.match(e.prompt,/当前事件引导/);A.ok(!e.prompt.includes('SECRET_NOT_IN_PROMPT'));A.ok(!e.prompt.includes('FUTURE_NOT_IN_PROMPT'));});
  e.arc.stopped=false;
  test('old arc autoplan yields while director is active',()=>A.equal(e.arc.usable(),false));e.arc.stopped=true;
  await A.rejects(T.studioAction(u,'st-next',''),/新的角色正文/);
  test('cannot advance stages repeatedly on same floor',()=>A.equal(e.repo.data.studio.active.index,0));
  e.settings.setEnabled('director',false);
  test('disabling director API module clears its prompt',()=>A.ok(!e.prompt.includes('当前事件引导')));e.settings.setEnabled('director',true);
  await T.studioAction(u,'st-event-stop','');
  test('cancelling removes prompt without deleting original planning data',()=>{A.equal(e.repo.data.studio.active,null);A.ok(!e.prompt.includes('当前事件引导'));A.ok(e.repo.data.arc);});
  const off=e.repo.data.contacts.find(c=>!e.repo.snapshot.present.includes(c.name));A.ok(off);
  await e.mutate(s=>{s.studio.roster=[{id:'roster-a',contactId:off.id,note:'本人知道的事',absent:null}];});
  test('unknown NPC presence is not treated as absent',()=>A.equal(T.studioEligible(e.repo.data,e.repo.snapshot).length,0));
  await T.studioAction(u,'st-roster-absent','roster-a');
  test('manual absence approval makes eligible offstage NPC available',()=>A.equal(T.studioEligible(e.repo.data,e.repo.snapshot).length,1));
  await e.mutate(s=>{s.studio.memories=[{id:'own',witnesses:[off.id],text:'OWN_WITNESS',evidence:'manual',...T.studioStamp(e.repo.snapshot)},{id:'private',witnesses:[s.contacts[0].id],text:'OTHER_PRIVATE_SECRET',evidence:'manual',...T.studioStamp(e.repo.snapshot)}];});
  const req=e.studio.requestFor('parallel',e.repo.data,e.repo.snapshot);
  test('parallel input includes only scoped witness memories, not player scene',()=>{const str=JSON.stringify(req.payload);A.match(str,/OWN_WITNESS/);A.ok(!str.includes('OTHER_PRIVATE_SECRET'));A.ok(!Object.hasOwn(req.payload,'context'));});
  await e.studio.generate('parallel');
  test('NPC output saved as noncanonical draft, never auto-injected',()=>{A.equal(e.repo.data.studio.drafts[0].kind,'parallel');A.equal(e.repo.data.studio.drafts[0].status,'pending');A.ok(!e.prompt.includes('这是演示草稿'));});
  const eligibleBefore=e.repo.data;
  test('new floor invalidates manual absence approval',()=>A.equal(T.studioEligible(eligibleBefore,{...e.repo.snapshot,floor:e.repo.snapshot.floor+1,lineage:[...e.repo.snapshot.lineage,'x']}).length,0));
  const quote=off.name+'在车站等车。';
  e.bridge.capture=()=>{const x=cap();return {...x,history:[{floor:x.floor,role:'assistant',text:quote}]};};await e.refresh();
  const bio=e.repo.data.contacts.find(c=>c.id===off.id).bio;
  e.router.call=async()=>JSON.stringify({updates:[{contactId:off.id,location:'车站',status:'等车',until:'',evidence:quote,personality:'MUST_NOT_OVERWRITE'}]});
  await e.studio.generate('world');const draft=e.repo.data.studio.drafts.find(r=>r.kind==='world');
  test('world extraction initially remains unapproved',()=>{A.ok(draft);A.equal(e.repo.data.studio.states.length,0);});
  await T.studioAction(u,'st-state-approve',draft.id);
  test('approved state updates whitelist only, never persona or MVU',()=>{A.equal(e.repo.data.studio.states[0].location,'车站');A.equal(e.repo.data.contacts.find(c=>c.id===off.id).bio,bio);A.ok(!JSON.stringify(e.repo.data.studio.states).includes('MUST_NOT_OVERWRITE'));});
  const before=JSON.stringify(e.repo.data.studio.drafts);
  e.router.call=async()=>JSON.stringify({updates:[{contactId:e.repo.snapshot.present[0],status:'错误',evidence:'not-in-source'}]});
  await A.rejects(e.studio.generate('world'));
  test('unanchored/unknown state update rejected atomically',()=>A.equal(JSON.stringify(e.repo.data.studio.drafts),before));
  e.router.call=async()=>'{broken';const attempts=e.repo.data.studio.attempts.length;
  await A.rejects(e.studio.generate('director'));
  test('failed generation counts once and does not destroy old candidates',()=>{A.equal(e.repo.data.studio.attempts.length,attempts+1);A.equal(e.repo.data.studio.pool.length,1);});
  let release;e.router.call=()=>new Promise(r=>release=r);
  const running=e.studio.generate('director').catch(err=>err);await wait(30);e.runner.cancel('user-stop');release(JSON.stringify(eventRaw));const error=await running;
  test('late output after stop is discarded',()=>{A.ok(error instanceof w.Error||error instanceof Error);A.equal(e.repo.data.studio.pool.length,1);});
  const running2=e.studio.generate('director').catch(err=>err);await wait(30);e.bridge.chat='demo-b';release(JSON.stringify(eventRaw));await running2;
  test('chat switch discards stale model output',()=>A.equal(e.repo.data.studio.pool.length,1));e.bridge.chat='demo-a';await e.refresh();
  let finishDialog;u.dialog=()=>new Promise(r=>finishDialog=r);const edit=T.studioAction(u,'st-rule-new','').catch(err=>err);await wait(10);e.bridge.chat='demo-b';finishDialog({title:'wrong-chat',keys:'',text:'no',enabled:true});await edit;
  test('open editor cannot save into a different chat',()=>A.ok(!T.studioRules(e.repo.data).some(r=>r.title==='wrong-chat')));e.bridge.chat='demo-a';u.dialog=originalDialog;await e.refresh();
  await e.mutate(s=>{s.studio.attempts=Array(12).fill(Date.now());});await A.rejects(e.studio.generate('director'),/12次/);
  test('shared manual generation budget enforced',()=>A.equal(e.repo.data.studio.attempts.length,12));
  e.router.call=api;
  u.open('studio');
  for(const tab of ['events','parallel','world','memories','settings']){await T.studioAction(u,'st-tab',tab);A.ok(u.shadow.querySelector('#main').textContent.length>50);}
  test('all five workbench pages render using native UI',()=>A.ok(u.shadow.querySelector('[data-action="st-preview"]')));
  console.log('STUDIO_OK: '+n+' cases; no external model/API calls');
 }finally{app.dispose();dom.window.close();}
})().catch(err=>{console.error(err);process.exitCode=1;dom.window.close();});
