// Native AVS regressions. No real provider requests. Node >=20 + jsdom.
const { JSDOM } = require('jsdom');
const fs = require('node:fs'), path = require('node:path'), A = require('node:assert/strict');
const input = process.argv[2] || path.join(__dirname, '..', 'tsukiyo-phone-2.5.0.js');
let js = fs.readFileSync(input, 'utf8');
js = js.slice(0, js.lastIndexOf('TsukiyoPhoneBundle.start('));
js = js.replace('    VERSION: () => VERSION,', '    AVSTest: () => ({ avsFresh, avsData, avsPrefix, avsCurrent, avsMerge, avsProjection, avsValidate, avsReadJson, avsNarrative, AVS_KNOWLEDGE, AVS_RULE_TITLES, AVS_FIELDS, fingerprint, handleVisualAction }),\n    VERSION: () => VERSION,');
const dom = new JSDOM('<!doctype html><html><body></body></html>', { runScripts: 'outside-only', pretendToBeVisual: true, url: 'https://phone.test/' });
const w = dom.window;
w.console = console;
w.eval(js + '\nwindow.B = TsukiyoPhoneBundle;');
const { B } = w, T = B.AVSTest;
let total = 0;
const ok = (name, f) => { f(); total++; console.log('PASS', name); };
const wait = ms => new Promise(r => setTimeout(r, ms));
const snap = { floor: 1, lineage: ['a','b'], history: [{ text: '小明穿着蓝色长衫' }], present: ['小明'] };
const meta = { floor: 1, prefix: T.avsPrefix(snap,1), source: '小明穿着蓝色长衫。' };
const data = [{ name: '小明', profile: { outfit: { '外衣': { value: '蓝色长衫', evidence: '小明穿着蓝色长衫' } } } }];
const rows = T.avsMerge([], data, meta);
ok('defaults: zero automatic requests, no injection', () => { A.equal(T.avsFresh().auto, false); A.equal(T.avsFresh().inject, false); });
ok('seven complete sections, exact evidence retained', () => { A.equal(Object.keys(rows[0].profile).length, 7); A.equal(rows[0].profile.outfit['外衣'].value,'蓝色长衫'); T.avsValidate({ ...T.avsFresh(), records: rows }); });
ok('unknown fields never become guessed defaults', () => A.equal(Object.keys(rows[0].profile.body).length,0));
ok('unanchored evidence cannot create data', () => A.equal(T.avsMerge([], [{name:'小明', profile:{face:{'眼睛':{value:'红色',evidence:'不存在的原文'}}}}],meta).length,0));
ok('unanchored character names rejected', () => A.throws(() => T.avsMerge([], [{name:'陌生人',profile:{}}],meta)));
ok('private body fields excluded', () => { const x = T.avsMerge([], [{name:'小明',profile:{body:{'乳房':{value:'不保存',evidence:'小明'},'体型':{value:'私处',evidence:'小明'}}}}],meta); A.equal(x.length,0); });
ok('same prefix usable, edited/deleted prefix invalid', () => { A.equal(T.avsCurrent({records:rows},snap).length,1); A.equal(T.avsCurrent({records:rows},{...snap,lineage:['edited','b']}).length,0); A.equal(T.avsCurrent({records:rows},{...snap,floor:0,lineage:['a']}).length,0); });
ok('version history supports rollback without mixing branches', () => { const older = T.avsMerge([], data, {...meta,floor:0,prefix:T.avsPrefix(snap,0)}); const newer = T.avsMerge(older,data,meta); A.equal(T.avsCurrent({records:newer},{...snap,lineage:['a','edited']})[0].floor,0); T.avsValidate({...T.avsFresh(),records:newer}); });
ok('all 290 entries available, only 13 workflow entries selected', () => { A.equal(T.AVS_KNOWLEDGE.length,290); A.equal(T.AVS_KNOWLEDGE.filter(r=>T.AVS_RULE_TITLES.includes(r.title.split('] ').at(-1))).length,13); });
ok('injection opt-in, scoped and no legacy estimates', () => { const s = {settings:{inject:true},visual:{...T.avsFresh(),records:rows}}; A.equal(T.avsProjection(s,snap),''); s.visual.inject=true; A.match(T.avsProjection(s,snap),/蓝色长衫/); A.equal(T.avsProjection(s,{...snap,present:[],history:[]}),''); s.settings.inject=false; A.equal(T.avsProjection(s,snap),''); });
ok('malformed / prototype / oversized schema rejected', () => { A.throws(()=>T.avsReadJson('{"characters":{},"__proto__":{}}')); A.throws(()=>T.avsValidate({...T.avsFresh(),records:[{name:'x'}]})); });
ok('narrative strips hidden updates without silently truncating', () => { const s='小明'.repeat(10000); A.equal(T.avsNarrative('<initvar>SECRET</initvar>'+s),s); });
(async () => {
 const app = B.start({mode:'demo',source:w});
 try {
  await wait(300);
  const e=app.engine,u=app.ui;
  e.scheduler.stop(); e.arc.stop(); e.memoryBook.stop(); clearInterval(e.timer);
  u.confirm=async()=>true;
  ok('stock upgrade version and module route',()=>{ A.equal(B.VERSION,'2.5.0'); A.equal(e.settings.route('visual').id,'tavern'); });
  await e.visual.tick();
  ok('idle tick consumes nothing by default',()=>A.equal(e.repo.data.visual.attempts.length,0));
  await e.visual.sync();
  ok('real engine queue commits a mock visual result',()=>{ A.equal(e.repo.data.visual.records.length,1); A.equal(e.repo.data.visual.records[0].name,'春山未夜'); A.equal(e.repo.data.visual.attempts.length,1); });
  u.open('visual');
  ok('native desktop entry and seven tabs render',()=>{ A.equal(u.shadow.querySelectorAll('[data-action="avs-tab"]').length,7); A.ok(u.shadow.querySelector('[data-action="avs-sync"]')); });
  await T.handleVisualAction(u,'avs-tab','state');
  ok('state details and escaped evidence render',()=>A.ok(u.shadow.textContent.includes('把稿纸挪离杯沿')));
  await T.handleVisualAction(u,'avs-inject');
  ok('injection switch changes compiled real-engine prompt',()=>A.match(e.prompt,/视觉连续性资料/));
  e.settings.setEnabled('visual',false);
  ok('module OFF removes prompt and rejects requests',()=>A.ok(!e.prompt.includes('视觉连续性资料')));
  await A.rejects(e.visual.sync(),/启用视觉/); e.settings.setEnabled('visual',true);
  u.open('visualRules');
  ok('rule library paginated at 12 not 290 DOM entries',()=>A.equal(u.shadow.querySelectorAll('details.card').length,12));
  u.avsRuleQuery='不存在的搜索词';u.render();
  ok('empty library search has a usable page',()=>A.match(u.shadow.textContent,/0 \/ 290 条/));
  const oldCall=e.router.call.bind(e.router);
  const saved=JSON.stringify(e.repo.data.visual.records);
  e.router.call=async()=>'{broken';
  await A.rejects(e.visual.sync());
  ok('failed JSON preserves records and consumes one attempt',()=>{ A.equal(JSON.stringify(e.repo.data.visual.records),saved); A.equal(e.repo.data.visual.attempts.length,2); });
  let release;
  e.router.call=()=>new Promise(r=>release=r);
  const running=e.visual.sync().catch(err=>err);
  await wait(40); e.runner.cancel('test-stop'); release('{"characters":[]}'); await running;
  ok('stop rejects late model result',()=>A.equal(JSON.stringify(e.repo.data.visual.records),saved));
  const running2=e.visual.sync().catch(err=>err);
  await wait(40); e.bridge.chat='demo-b'; release('{"characters":[]}'); await running2;
  ok('switching chat prevents stale write',()=>A.equal(JSON.stringify(e.repo.data.visual.records),saved));
  e.bridge.chat='demo-a';await e.refresh();
  // Fake a 9-assistant chat on the existing demo bridge to test staged rescan.
  const cap=e.bridge.capture.bind(e.bridge);
  const raw=Array.from({length:9},(_,i)=>({is_user:false,mes:`春山未夜穿着蓝色长衫。记录${i}`}));
  e.bridge.context=()=>({chat:raw});
  e.bridge.capture=()=>{const s=cap();const lineage=raw.map(m=>T.fingerprint(m.mes)); return {...s,floor:raw.length-1,tail:raw.length-1,lineage,signature:T.fingerprint(lineage),history:raw.slice(-8).map((m,i)=>({floor:i+1,role:'assistant',text:m.mes}))};};
  await e.refresh();
  const result=JSON.stringify({characters:[{name:'春山未夜',profile:{outfit:{'外衣':{value:'蓝色长衫',evidence:'春山未夜穿着蓝色长衫'}}}}]});
  e.router.call=async()=>result;
  const before=JSON.stringify(e.repo.data.visual.records);
  await e.visual.sync({rescan:true});
  ok('rescan first batch stages four rows, no destructive clear',()=>{ A.equal(e.repo.data.visual.scan.cursor,4); A.equal(JSON.stringify(e.repo.data.visual.records),before); });
  e.router.call=async()=>{throw Error('provider down');};
  await A.rejects(e.visual.sync({rescan:true}));
  ok('rescan failure preserves official archive and cursor',()=>{ A.equal(e.repo.data.visual.scan.cursor,4); A.equal(JSON.stringify(e.repo.data.visual.records),before); });
  e.router.call=async()=>result;
  await e.visual.sync({rescan:true});await e.visual.sync({rescan:true});
  ok('final rescan commits once and keeps rollback backup',()=>{ A.equal(e.repo.data.visual.scan,null); A.equal(JSON.stringify(e.repo.data.visual.backup.records),before); A.equal(e.repo.data.visual.records[0].profile.outfit['外衣'].value,'蓝色长衫'); });
  const realApi=e.bridge.api.bind(e.bridge);
  e.bridge.api=name=>name==='getVariables'?()=>({acgn_visual_v25:{characters:{x:{identity:{name:'旧人物'},profile:{face:{face_shape:{form:'圆脸'}},body:{bust:{form:'不得迁移'}},hair:{color:{data:'黑色'}}}}}}}):realApi(name);
  await e.visual.importLegacy();
  ok('actual v2.5 identity/profile schema migrates read-only',()=>{ const r=e.repo.data.visual.records.find(r=>r.name==='旧人物'); A.equal(r.profile.face['脸型'].source,'legacy'); A.equal(Object.keys(r.profile.body).length,0); });
  const count=e.repo.data.visual.records.length; await e.visual.importLegacy();
  ok('legacy migration deduplicates by name',()=>A.equal(e.repo.data.visual.records.length,count));
  e.bridge.api=name=>name==='__AVS_V25_RUNTIME__'?{}:realApi(name);
  await A.rejects(e.visual.sync(),/旧AVS/);
  ok('detected duplicate legacy runtime blocks extra billing',()=>A.ok(e.visual.oldRuntime()));
  e.bridge.api=realApi;
  await e.mutate(s=>{s.visual.auto=true;s.visual.seen=[];s.visual.attempts=[];});
  let calls=0;e.router.call=async()=>{calls++;throw Error('once');};e.visual.lastAutoKey='';
  await e.visual.tick();await e.visual.tick();
  ok('automatic failure not retried repeatedly on same turn',()=>A.equal(calls,1));
  e.visual.lastAutoKey='';await e.mutate(s=>{s.visual.seen=[];s.visual.attempts=Array(6).fill(Date.now());});await e.visual.tick();
  ok('six attempts per hour blocks automatic sync',()=>A.equal(calls,1));
  e.router.call=oldCall;
  console.log(`VISUAL_OK: ${total} assertions; no real model calls`);
 } finally { app.dispose();dom.window.close(); }
})().catch(err=>{console.error(err);process.exitCode=1;dom.window.close();});
