  // src/ui/views-life.js
  function lifeView(ui) {
    const s = ui.data;
    const tasks = s.tasks, done = tasks.filter((t) => t.done).length;
    return `<div class="pad"><div class="eyebrow">LIFE IS IN THE LITTLE THINGS</div><h2 style="font-size:24px;margin:6px 0 12px">把小事，过得认真。</h2><div class="mini-stat">${icon("coffee", 28)}<strong>${done}<small> / ${tasks.length}</small></strong><span>已经记下的心愿<br>不把日常变成刷分游戏</span></div><div class="buttons">${button(icon("spark", 14) + " 生成清单…", "auto-tasks", "", "primary")}${button(icon("plus", 14) + " 新心愿 / 项目", "new-task")}${button(icon("bag", 14) + " 随身物品", "go", "bag")}${button(icon("coffee", 14) + " 店务工具", "cafe-tools")}</div>${tasks.length ? tpDeleteBar("tasks", tasks.length, "清单") : ""}${section("慢慢完成", tasks.length ? `<div class="card">${tasks.map((t) => `<div class="task-row ${t.done ? "is-done" : ""}"><button class="task-check ${t.done ? "done" : ""}" data-action="task-progress" data-id="${e(t.id)}" aria-label="记录进度">${t.done ? icon("check", 15) : ""}</button><div class="task-text"><b>${e(t.title)}</b><small>${e(t.category || "生活")} · ${t.progress || 0}/${t.target || 1}${t.source && /^(正文生成|人物生成)/.test(t.source) ? " · " + e(t.source) : ""}${t.people?.length ? "<br>关于：" + e(t.people.map((id2) => contactName(s, id2)).join("、")) : ""}</small>${(t.target || 1) > 1 ? `<div class="progress"><i style="width:${Math.min(100, (t.progress || 0) / (t.target || 1) * 100)}%"></i></div>` : ""}</div><button class="icon-btn" data-action="task-delete" data-id="${e(t.id)}" aria-label="移除此项">${icon("more", 15)}</button></div>`).join("")}</div>` : empty("先选一件想做的小事", "也可以点“生成清单…”：按正文整理，或选几位角色各出几条。", "coffee"))}${hint("手机清单是记录，不会自动扣费、加好感或完成正文任务。店务工具仅在兼容卡的实际场景下记账。")}</div>`;
  }
  function notesView(ui) {
    const rows = ui.data.notes;
    return `<div class="pad"><div class="buttons" style="margin:0 0 10px">${button(icon("spark", 14) + " 生成备忘…", "auto-notes", "", "primary")}${button(icon("plus", 14) + " 写一张便签", "new-note")}</div>${rows.length ? tpDeleteBar("notes", rows.length, "便签") : ""}${rows.length ? `<div class="note-grid">${[...rows].reverse().map((n) => `<div class="note-card tp-note-wrap"><button type="button" class="tp-note-main" data-action="edit-note" data-id="${e(n.id)}"><h3>${e(n.title || "无题")}</h3><p>${e(n.text)}</p><small>${e(new Date(n.ts).toLocaleDateString("zh-CN"))}${n.source === "正文生成" ? " · 自动" : n.source === "人物生成" ? " · 人物" : ""}${n.people?.length ? " · " + e(n.people.map((id2) => contactName(ui.data, id2)).join("、")) : ""}</small></button><button type="button" class="icon-btn tp-note-del" data-action="delete-note" data-id="${e(n.id)}" aria-label="删除便签" title="删除便签">${icon("trash", 13)}</button></div>`).join("")}</div>` : empty("留一句给未来的自己", "也可以让手机从最近的正文里整理，或选几位角色各记几张。", "note")}</div>`;
  }
  function diaryView(ui) {
    const s = ui.data, tab = ui.route.tab || "all", filter = ui.route.author || "all", floorFilter = ui.route.floor || "all";
    const hearts = s.diary.filter((d) => d.kind === "heart");
    const diaries = s.diary.filter((d) => d.kind !== "heart");
    const basePool = tab === "heart" ? hearts : tab === "diary" ? diaries : s.diary;
    const authors = [...new Set(basePool.map((d) => d.author || "user"))];
    const heartFloors = [...new Set(hearts.map((d) => Number.isInteger(d.floor) ? d.floor : 0))].sort((a, b) => b - a);
    const rows = [...basePool].reverse().filter((d) => {
      if (filter !== "all" && (d.author || "user") !== filter) return false;
      if (tab === "heart" && floorFilter !== "all" && String(d.floor ?? 0) !== String(floorFilter)) return false;
      return true;
    });
    const delModule = tab === "heart" ? "heart" : tab === "diary" ? "diary" : "diary_all";
    const delLabel = tab === "heart" ? "恋爱心迹" : tab === "diary" ? "角色日记" : "日记与心迹";
    return `<div class="pad">
      <div class="segmented" style="margin-bottom:12px">
        <button class="${tab === "all" ? "active" : ""}" data-action="diary-tab" data-id="all">${icon("book", 13)} 全部 (${s.diary.length})</button>
        <button class="${tab === "heart" ? "active" : ""}" data-action="diary-tab" data-id="heart">${icon("heart", 13)} 恋爱心迹 (${hearts.length})</button>
        <button class="${tab === "diary" ? "active" : ""}" data-action="diary-tab" data-id="diary">${icon("edit", 13)} 角色日记 (${diaries.length})</button>
      </div>
      ${tab !== "diary" ? renderHeartTracePanel(ui) : ""}
      ${tab !== "heart" ? `<div class="card" style="margin-bottom:10px"><div class="row-top"><b>角色与玩家日记</b><small class="muted">每人只写本人知道的事</small></div><div class="buttons" style="margin-top:8px">${button(icon("spark", 14) + " 生成角色日记", "generate-diary", "", "primary")}${button(icon("people", 14) + " 随机 3 位", "random-diary")}${button(icon("edit", 14) + " 自己写", "new-diary")}</div></div>` : ""}
      ${authors.length > 1 ? `<div class="subnav" style="padding:6px 0 0"><button class="chip ${filter === "all" ? "active" : ""}" data-action="diary-filter" data-id="all">全部角色</button>${authors.map((a) => `<button class="chip ${filter === a ? "active" : ""}" data-action="diary-filter" data-id="${e(a)}">${e(a === "user" ? "我" : contactName(s, a))}</button>`).join("")}</div>` : ""}
      ${tab === "heart" && heartFloors.length > 1 ? `<div class="subnav" style="padding:6px 0 0"><button class="chip ${floorFilter === "all" ? "active" : ""}" data-action="diary-floor" data-id="all">全部楼层</button>${heartFloors.slice(0, 12).map((fl) => `<button class="chip ${String(floorFilter) === String(fl) ? "active" : ""}" data-action="diary-floor" data-id="${fl}">#${fl + 1}楼</button>`).join("")}</div>` : ""}
      ${basePool.length ? tpDeleteBar(delModule, basePool.length, delLabel) : ""}
      ${section(tab === "heart" ? "每楼层恋爱心迹" : tab === "diary" ? "留下来的日子" : "心迹与日记档案", rows.length ? rows.map((d) => renderDiaryEntryCard(ui, d)).join("") : empty(tab === "heart" ? "还没有记录下心迹" : "还没有写下今天", tab === "heart" ? "点上方“一键生成本楼心迹”，或开启每楼层自动生成，聆听角色在每层正文背后的悸动与潜台词。" : "普通的一天，也值得留下几行。", tab === "heart" ? "heart" : "book"))}
    </div>`;
  }
  function bagView(ui) {
    const s = ui.data, canonical = ui.snapshot.stat?.背包 || {};
    return `<div class="pad">${hint("主线物品来自角色卡变量；手机附注另存，不擅自修改真实物品数量。")}${Object.keys(canonical).length ? section("主线背包（只读）", Object.entries(canonical).map(([name, x]) => `<div class="card"><h3>${e(name)} ${tag("× " + (x.数量 ?? 1))}</h3><p class="muted tiny">${e(x.描述 || "")}</p><small>${e([x.获得时间, x.获得地点].filter(Boolean).join(" · "))}</small></div>`).join("")) : ""}<div class="buttons">${button(icon("plus", 14) + " 添加手机物品记录", "new-item", "", "primary")}</div>${s.items.length ? tpDeleteBar("items", s.items.length, "物品记录") : ""}${section("手机记录与备注", s.items.length ? s.items.map((x) => `<div class="card"><h3>${e(x.title)} ${tag("× " + x.quantity)}</h3><p class="muted tiny">${e(x.note || "")}</p><div class="buttons">${button("编辑", "edit-item", x.id)}${button("移除记录", "delete-item", x.id)}</div></div>`).join("") : empty("这里还没有手机物品记录", "记录不等于已经在剧情中获得。", "bag"))}</div>`;
  }
  function albumView(ui) {
    const rows = ui.data.album;
    return `<div class="pad">${hint("本地上传的照片存在本机手机专用图片库；用网址添加的照片只保存链接（图床、GitHub、Gitee 等），换设备也能显示。")}<div class="buttons" style="margin-bottom:10px">${button(icon("image", 14) + " 本地上传", "album-upload", "", "primary")}${button(icon("plus", 14) + " 用网址添加", "album-url")}</div>${rows.length ? tpDeleteBar("album", rows.length, "照片") : ""}${rows.length ? `<div class="photo-grid">${[...rows].reverse().map((p) => `<div class="photo-card tp-photo-wrap"><button type="button" class="tp-photo-main" data-action="photo" data-id="${e(p.id)}"><span class="photo"><img data-media="${e(p.mediaId)}" alt="${e(p.title || "留影")}"></span><small>${e(p.title || "这一刻")}</small></button><button type="button" class="icon-btn tp-photo-del" data-action="delete-photo" data-id="${e(p.id)}" aria-label="删除照片" title="删除照片">${icon("trash", 12)}</button></div>`).join("")}</div>` : empty("把某个瞬间留下来", "支持本地上传，也可以粘贴图床或 Git 仓库里的图片网址。", "image")}</div>`;
  }
  function placesView(ui) {
    const zone = ui.route.zone || "all", s = ui.data;
    const native = kusogaki_default.places.map((p) => ({ id: p.id, title: p.name, zone: p.zone || p.region, kind: p.kind || "地点", note: p.teaser, use: p.use, people: p.people || [], acts: p.acts || [], native: true }));
    const custom = (s.places || []).filter((p) => !native.some((n) => n.id === p.id)).map((p) => ({ ...p, zone: "CUSTOM", kind: "自建", people: [], acts: [] }));
    const all = [...native, ...custom], rows = zone === "all" ? all : all.filter((p) => p.zone === zone);
    const homes = PRESET ? native.filter((p) => p.zone === "HOME").slice(0, 3) : native.filter((p) => ["P04", "P06", "P07"].includes(p.id));
    const pick = ui.route.pick ? all.find((p) => p.id === ui.route.pick) : null;
    const zoneName = Object.fromEntries(PLACE_ZONES);
    const card = (p) => `<details class="details place"><summary>${icon("place", 15)} ${e(p.title)} <span class="tag ${p.zone === "HOME" ? "rose" : p.zone === "PLAY" ? "gold" : ""}">${e(p.kind)}</span></summary><p>${e(p.note || "")}${p.use ? "\n" + e(p.use) : ""}</p>${p.people.length ? `<p class="tiny muted">常在这里：${e(p.people.join("、"))}</p>` : ""}${p.acts.length ? `<div class="buttons">${p.acts.map((a, i) => button(e(a), "place-act", p.id + "|" + i)).join("")}</div>` : ""}<div class="buttons">${button("准备一个出行意向", "place-intent", p.id, "ghost")}${!p.native ? button("移除自建地点", "delete-place", p.id) : ""}</div></details>`;
    return `<div class="pad"><div class="map-hero"><svg viewBox="0 0 320 120" aria-hidden="true"><path d="M0 120 L120 30 L150 18 L175 30 L320 120Z" fill="#dfe8dc"/><path d="M128 28 L150 18 L172 28 L162 36 L150 30 L138 36Z" fill="#fff"/><path d="M0 104 C60 92 110 110 170 100 S280 92 320 104 L320 120 L0 120Z" fill="#c8d8c4"/><path d="M20 118 C80 96 150 116 210 98 S300 96 320 90" stroke="#9fbfd0" stroke-width="3" fill="none"/>${(PRESET ? [...homes, ...native.filter((p) => p.zone !== "HOME")].slice(0, 6).map((p, i) => [p.title.slice(0, 8), [150, 118, 188, 70, 226, 150][i], [92, 100, 104, 84, 88, 60][i]]) : [["月夜露台", 150, 92], ["春山家", 118, 100], ["龙石家", 188, 104], ["源道寺家", 70, 84], ["北高", 226, 88], ["朝雾高原", 150, 60]]).map(([n, x, y]) => `<circle cx="${x}" cy="${y}" r="3.5" fill="#4f7561"/><text x="${x + 5}" y="${y - 4}" font-size="8" fill="#355846">${n}</text>`).join("")}</svg><div><b>${e(PRESET ? PRESET.mapTitle || "生活地图" : "富士宫生活地图")}</b><small>${all.length} 个地点 · ${PRESET ? "住处、街上、玩乐、自然与远行" : "三位女主的家、镇上、玩乐、自然与远行"}</small></div></div><div class="buttons">${button(icon("spark", 14) + " 今天去哪玩", "place-random", "", "primary")}${button(icon("plus", 14) + " 添加地点", "new-place")}</div>${custom.length ? tpDeleteBar("places", custom.length, "自建地点") : ""}${pick ? `<div class="card pick"><div class="eyebrow">今日推荐 · ${e(zoneName[pick.zone] || "自建")}</div><h3 style="margin-top:6px">${e(pick.title)}</h3><p class="muted tiny">${e(pick.note || "")}</p>${pick.acts.length ? `<p class="tiny" style="margin-top:6px">可以：${e(pick.acts.join(" / "))}</p>` : ""}<div class="buttons">${button("就去这里", "place-intent", pick.id, "primary")}${button("换一个", "place-random")}</div></div>` : ""}${zone === "all" ? homes.length && section(PRESET ? "大家的住处" : "三位女主的家", `<div class="home-row">${homes.map((p) => `<button class="home-card" data-action="place-zone-home" data-id="${e(p.id)}"><b>${e(p.kind)}</b><small>${e(p.title)}</small></button>`).join("")}</div>`) : ""}<div class="subnav" style="padding:14px 0 4px">${[...PLACE_ZONES, ...custom.length ? [["CUSTOM", "自建"]] : []].map(([z, label]) => `<button class="chip ${zone === z ? "active" : ""}" data-action="place-zone" data-id="${z}">${e(label)}</button>`).join("")}</div>${hint("图鉴是地点参考，不代表已经到访；点玩法按钮只会把意向放进输入框，前往仍需剧情条件。")}${rows.length ? rows.map(card).join("") : empty("这个分类还没有地点", "可以自己添加一个。", "place")}</div>`;
  }

