  // src/ui/views-planner.js
  function planCard(ui, p, active) {
    const s = ui.data;
    return `<article class="card plan-card"><div class="plan-number">${e(p.tone || "日常")} · ${p.beats.length} 个留白的片段 ${active ? tag("已采用") : tag({ candidate: "待选择", paused: "已暂停", completed: "已收束", cancelled: "已取消" }[p.status] || p.status)}</div><h3 class="plan-title">${e(p.title)}</h3><p class="muted">${e(p.summary)}</p><div class="plan-members">${p.members.slice(0, 4).map((id2) => avatar(s.contacts.find((c) => c.id === id2), "small")).join("")}<span>${p.members.length ? e(p.members.map((id2) => contactName(s, id2)).join("、")) : "独自的小安排"}</span></div><div class="buttons">${button("看看这条方向 " + icon("arrow", 13), "plan-detail", p.id, active ? "primary" : "")}${!active && ["candidate", "paused"].includes(p.status) ? button("采用", "adopt-plan", p.id, "primary") : ""}${button("删除", "delete-plan", p.id, "danger")}</div></article>`;
  }
  function planDetailView(ui) {
    const s = ui.data, p = s.plans.find((p2) => p2.id === ui.route.id);
    if (!p) return empty("这条方向不在当前分支");
    const isActive = s.activePlan?.id === p.id, cursor = isActive ? s.activePlan.cursor : -1;
    return `<div class="pad">${tag(p.tone)}${tag(p.status === "active" ? "当前方向" : "未执行意向")}<h2 style="font-size:23px;margin:10px 0">${e(p.title)}</h2><p class="muted" style="font-size:12px;margin-bottom:16px">${e(p.summary)}</p>${hint("所有步骤最初都是未来机会。计划不会自动变成到访、消费、相认或关系承诺。")}<div class="steps">${p.beats.map((b, i) => `<div class="step ${i === cursor ? "current" : ""}"><small>${b.done ? "✓ 已有结果" : p.baseDate ? e(addDays(p.baseDate, b.day)) : "未来第 " + (b.day + 1) + " 天"}${i === cursor ? " · 当前一步" : ""}</small><h3>${e(b.title)}</h3><p>${e(b.scene)}</p><p class="tiny" style="margin-top:6px">前提：${e(b.trigger)}</p><details class="details" style="margin-top:10px;padding:9px"><summary>完成依据与可选意向</summary><p>${e(b.finish)}</p><div class="buttons">${b.choices.map((choice, index) => button(e(choice), "plan-intent", p.id + "|" + i + "|" + index)).join("")}</div>${b.evidence ? `<p>已记录依据：${e(b.evidence.quote || "玩家确认已发生")}</p>` : ""}</details></div>`).join("")}</div><div class="buttons">${isActive ? button("按正文核对进展", "review-plan", "", "primary") + button("确认当前一步已发生", "complete-step", p.id) + button("暂时暂停", "pause-plan", p.id) : ["candidate", "paused"].includes(p.status) ? button("采用这条方向", "adopt-plan", p.id, "primary") : ""}${["candidate", "paused"].includes(p.status) ? button("取消这条候选", "cancel-plan", p.id, "danger") : ""}</div>${hint("“放到输入框”的意向不会自动发送。自动核对需要正文原句，模型仍可能误判；可在手机中查看依据。")}</div>`;
  }
  function monthStart(day, offset = 0) {
    const y = Number(day.slice(0, 4)), m = Number(day.slice(5, 7));
    return new Date(Date.UTC(y, m - 1 + offset, 1)).toISOString().slice(0, 10);
  }
  function monthDays(start) {
    return new Date(Date.UTC(Number(start.slice(0, 4)), Number(start.slice(5, 7)), 0)).getUTCDate();
  }
  function agendaView(ui) {
    const s = ui.data, world = storyFor(s, ui.snapshot), today = world.date || (/* @__PURE__ */ new Date()).toISOString().slice(0, 10), month = Number(ui.route.month || 0), mStart = monthStart(today, month), selected = ui.route.date || (month ? mStart : today);
    const rows = s.agenda.filter((a) => a.date === selected || !a.date && selected === today);
    const plans = s.plans.filter((p) => p.status === "active" && p.baseDate).flatMap((p) => p.beats.filter((b) => addDays(p.baseDate, b.day) === selected).map((b) => ({ p, b })));
    const upcoming = s.agenda.filter((a) => a.date && a.date > selected && a.date <= addDays(selected, 30) && a.status !== "cancelled").sort((a, b) => a.date.localeCompare(b.date) || (a.time || "").localeCompare(b.time || "")).slice(0, 14);
    const statusTag = (a) => a.status === "event" ? tag(a.kind || "活动", a.kind === "节气" ? "" : a.kind === "校园" ? "rose" : "gold") : tag({ proposed: "待商量", confirmed: "已确认", completed: "已完成", cancelled: "已取消" }[a.status] || a.status) + (a.kind && a.kind !== "约定" ? tag(a.kind, "gold") : "");
    const card = (a, showDate) => `<div class="card"><div class="row-top">${statusTag(a)}<small>${showDate ? e(a.date + " " + dayLabel(a.date)) + " · " : ""}${e(a.time || "时间未定")}</small></div><h3 style="margin-top:7px">${e(a.title)}</h3><p class="muted tiny">${e(a.note || "没有额外说明")}</p>${(a.members || []).length ? `<p class="tiny muted" style="margin-top:4px">相关：${e(a.members.map((m) => contactName(s, m)).join("、"))}</p>` : ""}<div class="buttons">${a.status === "event" ? button("想一起去", "agenda-intent", a.id, "primary") + button("记为待商量", "agenda-propose", a.id) : ""}${a.status === "proposed" ? button("确认约定", "agenda-confirm", a.id) : ""}${a.status === "confirmed" ? button("确实完成了", "agenda-done", a.id) : ""}${["proposed", "confirmed"].includes(a.status) ? button("取消", "agenda-cancel", a.id) : ""}${button("删除", "agenda-delete", a.id, "danger")}</div></div>`;
    return `<div class="pad"><div class="eyebrow">${world.date ? "STORY TIME · " + e(world.origin) : "设备日历视图 · 非剧情日期"}</div><h2 class="weekday-title" style="margin-top:6px">${e(selected)} <small>${e(dayLabel(selected))}</small></h2><div class="month-head"><button class="chip" data-action="agenda-month" data-id="${month - 1}">‹ 上月</button><b>${e(mStart.slice(0, 4))}年${Number(mStart.slice(5, 7))}月</b><button class="chip" data-action="agenda-month" data-id="${month + 1}">下月 ›</button></div><div class="week-nav" style="justify-content:center">${month ? `<button class="chip active" data-action="agenda-month" data-id="0">回到剧情当月</button>` : ""}</div><div class="calendar-month">${["日", "一", "二", "三", "四", "五", "六"].map((w) => `<span class="wk">${w}</span>`).join("")}${Array.from({ length: new Date(mStart + "T00:00:00Z").getUTCDay() }, () => `<span class="mday blank"></span>`).join("")}${Array.from({ length: monthDays(mStart) }, (_, i) => {
      const d = addDays(mStart, i), list = s.agenda.filter((a) => a.date === d && a.status !== "cancelled"), fest = list.some((a) => a.status === "event"), n = list.length + arcDayEvents(s, d).length;
      return `<button class="mday ${d === selected ? "selected" : ""} ${d === today ? "today" : ""}" data-action="agenda-day" data-id="${d}" aria-label="${d}"><b>${i + 1}</b><i class="${fest ? "fest" : n ? "has" : ""}"></i></button>`;
    }).join("")}</div>${!world.date ? hint("主线还没有提供日期。可手动设置剧情日期；这里只显示设备日历作为浏览导航，不自动推进剧情。", true) : ""}<div class="buttons">${button(icon("spark", 14) + " 一键生成本月节日", "gen-festivals", mStart, "primary")}${button(icon("plus", 14) + " 新建约定", "new-agenda")}${button("剧情日期", "story-date")}</div>${s.agenda.length ? tpDeleteBar("agenda", s.agenda.length, "日程与约定") : ""}<p class="tiny muted" style="margin-top:6px">一键生成：为当前显示的整个月份生成风俗、庆典、节气、游玩、校园活动，以及已知人物可能提出的邀约（只是待商量）。接口不可用时自动改用本卡内置节庆表。</p>${section("这一天", rows.length ? rows.map((a) => card(a, false)).join("") : empty("这一天还很宽敞", "没有安排，也是一种安排。", "calendar"))}${arcCalendarHtml(s, selected)}${plans.length ? section("方向里的建议 · 非正式约定", plans.map(({ p, b }) => `<button class="card" style="display:block;width:100%;text-align:left" data-action="plan-detail" data-id="${e(p.id)}">${tag("未执行计划", "gold")}<h3 style="margin-top:7px">${e(b.title)}</h3><p class="muted tiny">${e(b.scene)}</p></button>`).join("")) : ""}${upcoming.length ? section("接下来 30 天", upcoming.map((a) => card(a, true)).join("")) : ""}</div>`;
  }
  var KIND_LABEL = { phone_fact: "交流事实", narrative_fact: "正文事实", promise: "未完约定", manual: "手工记录" };
  var clock = (ts) => ts ? new Date(ts).toLocaleString("zh-CN", { hour12: false, month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" }) : "尚未同步";
  function bookCard(ui) {
    const mb = ui.engine.memoryBook, b = mb.info();
    if (!b.supported) return `<div class="card">${hint("记忆世界书需要酒馆助手（世界书接口）。当前环境没有检测到，记忆仍照常保存在手机里，并通过“正文注入”进入剧情。", true)}</div>`;
    if (!b.linked) return `<div class="card book-card"><h3>记忆世界书</h3><p class="tiny muted">把手机记忆同步到一本单独的世界书（默认名「${e(ui.data.memoryBook.name || "角色卡名-小手机记忆")}」），可以在酒馆里直接查看、修改、增删，手机和世界书<b>双向同步</b>；世界书绑定到角色卡后，记忆就以世界书条目的方式进入正文。</p><div class="buttons">${button(icon("book", 14) + " 创建并同步", "memory-book-create", "", "primary")}${button(icon("spark", 14) + " AI 生成一份记忆", "memory-book-generate")}</div></div>`;
    return `<div class="card book-card"><div class="row-top"><h3>${e(b.name)}</h3><span>${tag(b.scope === "chat" ? "仅本聊天" : "整张角色卡共用", "gold")} ${tag(b.bound ? "已绑定" : "未绑定", b.bound ? "" : "rose")}</span></div><p class="tiny muted">已同步 ${b.linkedCount} / ${b.total} 条 · 上次 ${e(clock(b.lastSyncAt))}${b.phase === "syncing" ? " · 正在同步…" : ""}</p>${b.lastError ? hint(b.lastError, true) : ""}${b.confirm ? `<div class="hint warning">世界书里有 ${b.confirm.count} 条记忆被删除或整本被清空。要让手机也跟着删除，还是以手机记忆重建世界书？</div><div class="buttons">${button("手机也一起删除", "memory-book-accept-delete", "", "danger")}${button("以手机记忆重建世界书", "memory-book-rebuild", "", "primary")}</div>` : ""}<div class="buttons">${button(icon("shuffle", 14) + " 立即同步", "memory-book-sync", "", "primary")}${button(icon("spark", 14) + " AI 生成记忆", "memory-book-generate")}${b.bound ? "" : button("重新绑定", "memory-book-rebind")}${b.lastError && /不存在|删除了/.test(b.lastError) ? button("以手机记忆重建世界书", "memory-book-rebuild") : ""}${button("停止同步", "memory-book-unlink")}</div>${switchRow("自动同步", "手机改了就写进世界书；世界书改了就拉回手机", "memory-book-autosync", b.autoSync)}</div>`;
  }
  function memoryCard(ui, m) {
    const s = ui.data, viaBook = s.memoryBook?.linked && m.wb;
    return `<div class="card memory-card ${m.enabled === false ? "is-off" : ""}"><div class="row-top"><div>${tag(KIND_LABEL[m.kind] || "记忆")}${m.resolved ? tag("已核对结束") : ""}${viaBook ? tag("世界书", "gold") : ""}${m.bb ? tag("柏宝书", "gold") : ""}${m.enabled === false ? tag("已停用", "rose") : ""}</div></div>${m.title ? `<h3 style="margin-top:8px">${e(memoryTitle(m))}</h3>` : ""}<p style="margin-top:8px">${e(m.text)}</p>${m.keys?.length ? `<p class="muted tiny" style="margin-top:6px">关键词：${e(m.keys.join("、"))}</p>` : ""}<p class="muted tiny" style="margin-top:9px">知情：${e(m.audience.map((id2) => contactName(s, id2)).join("、") || "待核对")}</p><details class="details" style="margin:9px 0 0;padding:8px"><summary>来源</summary><p>${e(m.sources.map((x) => x.quote || x.note || x.messageId || "手工确认").join("\n"))}</p></details>${m.prev ? `<div class="hint warning" style="margin-top:8px">两边同时改过，已采用世界书版本。手机里被覆盖的旧内容：「${e(m.prev.text.slice(0, 80))}」</div>` : ""}<div class="buttons">${button("编辑", "memory-edit", m.id)}${button(m.enabled === false ? "启用" : "停用", "memory-toggle", m.id)}${m.prev ? button("恢复旧内容", "memory-restore-prev", m.id) : ""}${m.kind === "promise" && !m.resolved ? button("约定结束", "resolve-memory", m.id) : ""}${button("删除", "memory-delete", m.id, "danger")}</div></div>`;
  }
  function memoryView(ui) {
    const s = ui.data;
    return `<div class="pad"><div class="mini-stat">${icon("memory", 28)}<strong>${s.memories.length}</strong><span>条有范围的记忆<br>${s.summaries.length} 份会话摘要</span></div>${bookCard(ui)}${baibaiMemoryCard()}${msCard(ui)}${memApiCard(ui)}${memApiPreviewCard(ui)}${hint("原文、来源、知情者分别保留。邀请不是已经发生的行动；私人经历不会自动广播给其他角色。")}<div class="buttons">${button("整理新的交流", "summarize", "", "primary")}${button("查看正文注入", "inspect-injection")}${button(icon("plus", 14) + " 新增记忆", "new-memory")}</div>${s.memories.length ? tpDeleteBar("memories", s.memories.length, "记忆") : ""}${section("明确记录的事", s.memories.length ? [...s.memories].reverse().map((m) => memoryCard(ui, m)).join("") : empty("还没有需要特别记下的事", "可以手动新增，或点“AI 生成记忆”从正文里提炼；摘要只是长线辅助。", "book"))}${s.summaries.length ? section("滚动摘要", s.summaries.slice(-8).reverse().map((m) => `<details class="details"><summary>${e(s.threads.find((t) => t.id === m.threadId)?.title || "旧会话")} · 摘要</summary><p>${e(m.text)}</p></details>`).join("")) : ""}</div>`;
  }

