const fs=require('fs'),path=require('path'),A=require('node:assert/strict');
let code=fs.readFileSync(path.join(__dirname,'../dist/tsukiyo-phone-v2.9.6.js'),'utf8').replace(/TsukiyoPhoneBundle\.start\([^)]*\);?\s*$/,'');
const names=['freshPhone','BookStudio','MemoryBook','SoulStudio','soulEnsure','soulAddEntry','soulData','soulRow','soulCharView','reviewAction','reviewPick','reviewSoulDelete','reviewBookSig','planMemorySync','fingerprint','bookFreshState','handleAction','normalizePhone'];
code=code.replace('return __toCommonJS(index_exports);','__export(index_exports,{'+names.map(n=>n+':()=>'+n).join(',')+'});return __toCommonJS(index_exports);');
const T=new Function(code+';return TsukiyoPhoneBundle;')();let count=0;const clone=x=>JSON.parse(JSON.stringify(x));
const pass=(name,fn)=>{fn();count++;console.log('PASS',name);};const test=async(name,fn)=>{await fn();count++;console.log('PASS',name);};
function engine(){
 const books={'测试书':[]};let uid=0;const e={now:{owner:'chat-a',signature:'sig-a',floor:1,history:[],present:[],character:{name:'测试卡'}},win:{},emit(){},settings:{secrets:()=>[],isEnabled:()=>true,data:{},route:()=>({id:'tavern'})},runner:{busy:false},router:{call:async()=>'{"性格":["安静"]}'}};
 e.bridge={capture:()=>clone(e.now),same:s=>s.owner===e.now.owner&&s.signature===e.now.signature,wbSupported:()=>true,wbWritable:()=>true,isBusy:()=>false,wbNames:async()=>Object.keys(books),wbRead:async n=>clone(books[n]),wbCreate:async n=>{books[n]=[];return true;},wbBind:async()=>true,wbBindings:async()=>({primary:'测试书',additional:[],chat:'',global:[]}),wbUpdate:async(n,fn)=>{const rows=await fn(clone(books[n]));books[n]=rows.map(r=>({uid:'u'+(++uid),...r}));return clone(books[n]);},setPrompt:(text)=>{e.injected=text;return true;}};
 e.repo={data:T.freshPhone(),snapshot:clone(e.now),mutate:async(fn,opts={})=>{if(opts.snapshot)A.ok(e.bridge.same(opts.snapshot),'repository snapshot');if(opts.guard)A.ok(opts.guard(e.repo.data));const d=clone(e.repo.data);await fn(d,e.now);e.repo.data=d;return d;}};
 e.repo.data.contacts=[{id:'npc-a',name:'阿青',age:null,bio:'温和',status:'在家',recognized:true,reachable:true,aliases:[],references:[]}];
 e.repo.data.diary=[{id:'diary-a',title:'昨日',text:'看过落日',date:'2026-10-06',author:'user',ts:1}];
 e.bookStudio=new T.BookStudio(e);e.memoryBook=new T.MemoryBook(e);e.soul=new T.SoulStudio(e);e.books=books;e.stop=()=>{e.bookStudio.stop();e.memoryBook.stop();};return e;
}
function uiFor(e){return {engine:e,get data(){return e.repo.data},get snapshot(){return e.repo.snapshot},route:{view:'soul',id:''},go(v,id=''){this.route={view:v,id}},render(){},notify(){},confirm:async()=>true};}
(async()=>{
 await test('archive button carries exact role name, including punctuation',async()=>{const e=engine(),u=uiFor(e),name='阿青 | A & B';T.soulEnsure(e.repo.data.soul,name);const html=T.soulRow(u,e.repo.data.soul.roster[name]);A.ok(html.includes('data-action="review-soul-open"'));A.ok(html.includes('data-id="阿青 | A &amp; B"'));await T.reviewAction(u,'review-soul-open',name);A.equal(u.route.id,name);A.ok(!T.soulCharView(u).includes('可能已被删除'));e.stop();});
 pass('reserved role names rejected',()=>{for(const name of ['__proto__','constructor','prototype'])A.throws(()=>T.soulEnsure(T.freshPhone().soul,name));});
 await test('bulk soul deletion leaves contacts and other roles intact',async()=>{const e=engine(),s=e.repo.data;for(const n of ['阿青','乙'])T.soulEnsure(s.soul,n);s.soul.last.actors=['阿青','乙'];s.soul.history=[{actors:[{name:'阿青',text:'a'},{name:'乙',text:'b'}]}];T.reviewSoulDelete(s,['阿青']);A.equal(s.contacts.length,1);A.ok(s.soul.roster['乙']);A.equal(s.soul.roster['阿青'],undefined);A.deepEqual(s.soul.last.actors,['乙']);A.equal(s.soul.history[0].actors.length,1);e.stop();});
 await test('preview pages preserve selections across pages',async()=>{const e=engine(),u=uiFor(e);let n=0;u.dialog=async(title,html)=>{A.ok(html.includes('展开完整条目预览'));return ++n===1?{choice:'next',members:['k0']}:{choice:'apply',members:['k21']}};const rows=Array.from({length:25},(_,i)=>({key:'k'+i,name:'条目'+i,content:'正文'+i}));A.deepEqual((await T.reviewPick(u,'选择',rows)).map(x=>x.key),['k0','k21']);e.stop();});
 await test('cancel does not return a destructive selection',async()=>{const e=engine(),u=uiFor(e);u.dialog=async()=>null;A.equal(await T.reviewPick(u,'取消',[{key:'a',name:'a'}]),null);e.stop();});
 await test('dialog chat switch rejects old selection',async()=>{const e=engine(),u=uiFor(e);u.dialog=async()=>{e.now.owner='other';return {choice:'apply',members:['a']}};await A.rejects(T.reviewPick(u,'切换',[{key:'a',name:'a'}]),/变化/);e.stop();});
 await test('preview escapes markup and script-like role names',async()=>{const e=engine(),u=uiFor(e);u.dialog=async(t,h)=>{A.ok(h.includes('&lt;script&gt;'));A.ok(!h.includes('<script>'));return null;};await T.reviewPick(u,'转义',[{key:'x',name:'<script>',content:'<script>'}]);e.stop();});
 await test('all-source preview includes disabled categories without enabling them',async()=>{const e=engine();e.repo.data.notes=[{id:'n1',title:'便签',text:'正文'}];A.ok(!e.bookStudio.recordsFor(e.repo.data,e.now).some(x=>x.src==='notes'));A.ok(e.bookStudio.recordsFor(e.repo.data,e.now,{all:true}).some(x=>x.src==='notes'));A.equal(e.repo.data.bookSync.sources.notes,false);e.stop();});
 await test('first persona-only sync never writes diary',async()=>{const e=engine();await e.bookStudio.link({name:'新书',sources:Object.fromEntries(Object.keys(e.repo.data.bookSync.sources).map(k=>[k,k==='persona']))});A.equal(e.books['新书'].length,1);A.equal(e.books['新书'][0].extra.tsukiyo.kind,'persona');e.stop();});
 await test('bulk remove persists exclusion, preserves originals and foreign entries',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});e.books['测试书'].push({uid:'foreign',name:'其他扩展',content:'KEEP'});const before=clone(e.repo.data.contacts);const sig=T.reviewBookSig(e.books['测试书']);await e.bookStudio.removeSelected(['persona:npc-a'],{remoteSig:sig});A.deepEqual(e.repo.data.contacts,before);A.ok(e.books['测试书'].some(r=>r.uid==='foreign'));A.ok(!e.books['测试书'].some(r=>r.extra?.tsukiyo.key==='persona:npc-a'));await e.bookStudio.sync({force:true});A.ok(!e.books['测试书'].some(r=>r.extra?.tsukiyo.key==='persona:npc-a'));e.stop();});
 await test('restoring exclusion allows intentional re-creation',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});await e.bookStudio.removeSelected(['persona:npc-a']);e.repo.data.bookSync.excludedKeys=[];await e.bookStudio.sync({force:true});A.ok(e.books['测试书'].some(r=>r.extra?.tsukiyo.key==='persona:npc-a'));e.stop();});
 await test('remote edit after preview prevents deletion',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});const sig=T.reviewBookSig(e.books['测试书']);e.books['测试书'][0].content='最新修改';await A.rejects(e.bookStudio.removeSelected(['persona:npc-a'],{remoteSig:sig}),/变化/);A.ok(!e.repo.data.bookSync.excludedKeys.length);e.stop();});
 await test('write failure retains exclusion for retry, never deletes source',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});e.bridge.wbUpdate=async()=>{throw Error('offline')};await A.rejects(e.bookStudio.removeSelected(['persona:npc-a']),/offline/);A.ok(e.repo.data.bookSync.excludedKeys.includes('persona:npc-a'));A.equal(e.repo.data.contacts.length,1);e.stop();});
 await test('long persona content uses truncated hash and does not rewrite endlessly',async()=>{const e=engine();e.repo.data.contacts[0].bio='长'.repeat(10000);await e.bookStudio.link({name:'测试书'});const res=await e.bookStudio.sync({force:true});A.equal(res.stats.updated,0);A.equal(e.repo.data.contacts[0].bio.length,10000);e.stop();});
 await test('remote persona edits become references and remain stable next sync',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});const r=e.books['测试书'].find(r=>r.extra.tsukiyo.kind==='persona');r.content='世界书新资料';const a=await e.bookStudio.sync({force:true});A.equal(a.stats.pulled,1);A.equal(e.repo.data.contacts[0].bio,'温和');A.ok(e.repo.data.contacts[0].references.some(x=>x.content==='世界书新资料'));const b=await e.bookStudio.sync({force:true});A.equal(b.stats.updated,0);A.equal(b.stats.pulled,0);A.equal(e.books['测试书'].find(r=>r.extra.tsukiyo.kind==='persona').content,'世界书新资料');e.stop();});
 await test('simultaneous local/remote edits preserve both instead of silent overwrite',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});e.repo.data.contacts[0].bio='本地新资料';e.books['测试书'].find(r=>r.extra.tsukiyo.kind==='persona').content='远端新资料';const a=await e.bookStudio.sync({force:true});A.equal(a.stats.conflicts,1);A.equal(e.repo.data.contacts[0].bio,'本地新资料');A.equal(e.books['测试书'].find(r=>r.extra.tsukiyo.kind==='persona').content,'远端新资料');e.stop();});
 await test('soul remote edits are not falsely counted as imported',async()=>{const e=engine();T.soulEnsure(e.repo.data.soul,'阿青');T.soulAddEntry(e.repo.data.soul,'阿青','性格','温柔');e.repo.data.bookSync.sources.soul=true;await e.bookStudio.link({name:'测试书'});const r=e.books['测试书'].find(r=>r.extra.tsukiyo.kind==='soul'),hash=r.extra.tsukiyo.hash;r.content='远端修改';const a=await e.bookStudio.sync({force:true});A.equal(a.stats.pulled,0);A.equal(a.stats.skipped,1);A.equal(e.books['测试书'].find(r=>r.extra.tsukiyo.kind==='soul').extra.tsukiyo.hash,hash);e.stop();});
 await test('memory plan imports selected UID only and ignores workshop rows',async()=>{const rows=[{uid:1,name:'一',content:'记忆一'},{uid:2,name:'二',content:'记忆二'},{uid:3,name:'工坊',content:'不能作记忆',extra:{tsukiyo:{source:'book-studio',key:'persona:a'}}}];const p=T.planMemorySync([],rows,{allowedImportUids:[2]});A.deepEqual(p.import.map(r=>r.uid),[2]);A.equal(p.deleteWB.length,0);});
 await test('memory link reuses workshop book without creating another book',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});e.books['测试书'].push({uid:'m1',name:'可选记忆',content:'曾经看灯'},{uid:'m2',name:'不选',content:'不要导入'});await e.memoryBook.link({name:'测试书',acceptExisting:true,importUids:['m1']});A.deepEqual(Object.keys(e.books),['测试书']);A.equal(e.repo.data.memories.length,1);A.equal(e.repo.data.memories[0].text,'曾经看灯');A.ok(e.books['测试书'].some(r=>r.uid==='m2'));e.stop();});
 await test('late analysis cannot resurrect deleted soul role',async()=>{const e=engine();e.repo.data.soul.enabled=true;T.soulEnsure(e.repo.data.soul,'阿青');let finish;e.router.call=()=>new Promise(r=>finish=r);const run=e.soul.analyze('阿青');while(!finish)await new Promise(r=>setImmediate(r));T.reviewSoulDelete(e.repo.data,['阿青']);finish('{"性格":["迟到"]}');await A.rejects(run,/删除|修改/);A.equal(e.repo.data.soul.roster['阿青'],undefined);e.stop();});
 await test('late roleplay cannot inject a deleted role',async()=>{const e=engine();e.repo.data.soul.enabled=true;T.soulEnsure(e.repo.data.soul,'阿青');let finish;e.router.call=()=>new Promise(r=>finish=r);const run=e.soul.roleplay({names:['阿青']});while(!finish)await new Promise(r=>setImmediate(r));T.reviewSoulDelete(e.repo.data,['阿青']);finish('{"text":"迟到的推演"}');await A.rejects(run,/删除|修改/);A.ok(!e.injected);e.stop();});
 await test('soul link request rejects chat change before model call',async()=>{const e=engine();e.repo.data.soul.enabled=true;T.soulEnsure(e.repo.data.soul,'阿青');e.bridge.wbBindings=async()=>{e.now.owner='other';return {additional:[]}};let calls=0;e.router.call=async()=>{calls++;return '{}'};await A.rejects(e.soul.analyze('阿青'),/变化/);A.equal(calls,0);e.stop();});
 await test('workshop rejects chat switch during remote read without writing either chat',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});const old=clone(e.books);e.bridge.wbRead=async n=>{e.now.owner='other';return clone(e.books[n])};await A.rejects(e.bookStudio.sync({force:true}),/变化/);A.deepEqual(e.books,old);e.stop();});
 await test('phone-to-soul command mutates the saved transaction draft',async()=>{const e=engine(),u=uiFor(e);e.repo.data.soul.enabled=true;T.soulEnsure(e.repo.data.soul,'阿青');e.repo.data.threads=[{id:'t',kind:'direct',members:['npc-a'],messages:[{role:'user',text:'一起喝茶'}]}];await T.handleAction(u,'soul-pull-phone','阿青');A.ok(e.repo.data.soul.roster['阿青'].sections['记忆'].some(r=>r.text.includes('一起喝茶')));e.stop();});
 await test('connecting an existing book preserves unmatched workshop entries from other chats',async()=>{const e=engine();e.books['测试书'].push({uid:'other-chat',name:'另一存档人物',content:'保留内容',extra:{tsukiyo:{source:'book-studio',key:'persona:other',kind:'persona',hash:'legacy'}}});await e.bookStudio.link({name:'测试书',acceptExisting:true});await e.bookStudio.sync({force:true});await e.bookStudio.cleanOrphans();A.ok(e.books['测试书'].some(r=>r.uid==='other-chat'));e.stop();});
 await test('memory sync rejects chat switch during remote read',async()=>{const e=engine();await e.memoryBook.link({name:'测试书'});const old=clone(e.books);e.bridge.wbRead=async n=>{e.now.owner='other';return clone(e.books[n])};await A.rejects(e.memoryBook.sync({force:true}),/变化/);A.deepEqual(e.books,old);e.stop();});
 await test('memory sync rejects local edit during remote read',async()=>{const e=engine();await e.memoryBook.link({name:'测试书'});e.bridge.wbRead=async n=>{e.repo.data.memoryBook.autoSync=false;return clone(e.books[n])};await A.rejects(e.memoryBook.sync({force:true}),/配置已变化/);e.stop();});
 await test('selected memory UIDs persist in card auto-link settings',async()=>{const e=engine(),map=new Map();e.win.localStorage={getItem:k=>map.get(k),setItem:(k,v)=>map.set(k,v)};e.books['测试书']=[{uid:'a',name:'选中',content:'a'},{uid:'b',name:'未选',content:'b'}];await e.memoryBook.link({name:'测试书',acceptExisting:true,importUids:['a']});A.deepEqual(e.memoryBook.saved()['测试卡'].importUids,['a']);e.stop();});
 await test('memory preview bulk deletion queues only selected linked record for remote removal',async()=>{const e=engine(),u=uiFor(e);e.books['测试书']=[{uid:'a',name:'A',content:'要删除的记忆'},{uid:'b',name:'B',content:'保留的记忆'}];await e.memoryBook.link({name:'测试书',acceptExisting:true,importUids:['a','b']});const id=e.repo.data.memories.find(m=>m.text==='要删除的记忆').id;u.dialog=async()=>({choice:'apply',members:[id]});await T.reviewAction(u,'review-memory-manage','');A.equal(e.repo.data.memories.length,1);await e.memoryBook.sync({force:true});A.ok(!e.books['测试书'].some(r=>r.uid==='a'));A.ok(e.books['测试书'].some(r=>r.uid==='b'));e.stop();});
 console.log('REVIEW_OK: '+count+' regression cases; mocked host/model only');
})().catch(e=>{console.error(e);process.exit(1)});
