const fs=require('fs'),path=require('path'),A=require('node:assert/strict'),{JSDOM}=require('jsdom');
let code=fs.readFileSync(require('./lib/dist.cjs').distFile(),'utf8').replace(/TsukiyoPhoneBundle\.start\([^)]*\);?\s*$/,'');code=code.replace('return __toCommonJS(index_exports);','__export(index_exports,{soulEnsure:()=>soulEnsure});return __toCommonJS(index_exports);');
const dom=new JSDOM('<html><body></body></html>',{runScripts:'outside-only',pretendToBeVisual:true,url:'https://review.test/'}),w=dom.window;w.eval(code+';window.B=TsukiyoPhoneBundle;');const app=w.B.start({mode:'demo',source:w}),delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<150;i++){if(fn())return;await delay(10);}throw Error('UI timeout: '+app.ui.shadow.getElementById('notices').textContent);}
const find=(act,id,scope)=>[...(scope||app.ui.shadow).querySelectorAll('[data-action]')].find(n=>n.dataset.action===act&&(id===undefined||n.dataset.id===id));
function click(act,id){const el=find(act,id);A.ok(el,'missing button '+act+' '+id);el.click();}
function submit(){const form=app.ui.shadow.querySelector('#modals form');A.ok(form);form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
(async()=>{try{
 await until(()=>app.engine.state==='ready');const e=app.engine,u=app.ui;e.scheduler.stop();e.arc.stop();e.memoryBook.stop();e.bookStudio.stop();e.soul.stop();e.ms.stop();clearInterval(e.timer);e.memoryBook.stopped=false;e.bookStudio.stopped=false;e.bookStudio.schedule=()=>{};e.memoryBook.schedule=()=>{};
 const books={'工作簿':[]};let next=0;Object.assign(e.bridge,{wbSupported:()=>true,wbWritable:()=>true,wbNames:async()=>Object.keys(books),wbRead:async n=>JSON.parse(JSON.stringify(books[n])),wbBind:async()=>true,wbBindings:async()=>({primary:'工作簿',additional:[],chat:'',global:[]}),wbCreate:async n=>{books[n]=[];return true},wbUpdate:async(n,fn)=>{books[n]=fn(JSON.parse(JSON.stringify(books[n]))).map(r=>({uid:'e'+(++next),...r}));return JSON.parse(JSON.stringify(books[n]));}});
 await e.mutate(s=>{s.soul.enabled=true;w.B.soulEnsure(s.soul,'甲 | 乙');w.B.soulEnsure(s.soul,'留下的人');});
 e.router.call=async()=>JSON.stringify({性格:['档案确实已经生成']});await e.soul.analyze('甲 | 乙');
 u.open('soul');await delay(500);click('review-soul-open','甲 | 乙');await until(()=>u.route.view==='soulChar');A.equal(u.route.id,'甲 | 乙');A.ok(u.shadow.getElementById('main').textContent.includes('档案确实已经生成'));A.ok(!u.shadow.textContent.includes('可能已被删除'));
 console.log('UI_PASS generated archive -> actual button -> correct named archive');
 u.go('soul');click('review-soul-delete');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));const checks=[...u.shadow.querySelectorAll('#modals input[name="members"]')];checks.find(n=>n.value==='甲 | 乙').checked=true;click('modal-choice','apply');await until(()=>u.shadow.querySelector('#modals [data-id="yes"]'));click('modal-choice','yes');await until(()=>!e.repo.data.soul.roster['甲 | 乙']);A.ok(e.repo.data.soul.roster['留下的人']);A.equal(e.repo.data.contacts.length,3);
 console.log('UI_PASS real checkbox/confirmation deletes only selected soul role');
 await e.bookStudio.link({name:'工作簿'});u.go('book');click('review-book-manage');await until(()=>u.shadow.querySelector('#modals select[name="kind"]'));u.shadow.querySelector('#modals select[name="kind"]').value='persona';submit();await until(()=>u.shadow.querySelector('#modals input[name="members"]'));const selected=u.shadow.querySelector('#modals input[name="members"]');const key=selected.value;A.ok(key.startsWith('persona:'));A.ok(u.shadow.querySelector('#modals details pre').textContent.length>0);selected.checked=true;click('modal-choice','apply');await until(()=>find('modal-choice','yes'));click('modal-choice','yes');await until(()=>e.repo.data.bookSync.excludedKeys.includes(key));A.ok(!books['工作簿'].some(r=>r.extra?.tsukiyo?.key===key));A.equal(e.repo.data.contacts.length,3);
 await e.bookStudio.sync({force:true});A.ok(!books['工作簿'].some(r=>r.extra?.tsukiyo?.key===key));console.log('UI_PASS workshop category preview -> selected removal -> no automatic resurrection; contacts preserved');
 books['工作簿'].push({uid:'manual-a',name:'读入的记忆',content:'曾一起读书'},{uid:'manual-b',name:'不读入的记忆',content:'保留在世界书'});
 u.go('memories');click('review-memory-connect');await until(()=>u.shadow.querySelector('#modals select[name="name"]'));A.equal(u.shadow.querySelector('#modals select[name="name"]').value,'工作簿');submit();await until(()=>u.shadow.querySelector('#modals input[name="members"]'));A.equal(u.shadow.querySelectorAll('#modals input[name="members"]').length,2);u.shadow.querySelector('#modals input[name="members"]').checked=true;click('modal-choice','apply');await until(()=>e.repo.data.memoryBook.linked&&e.repo.data.memories.some(m=>m.text==='曾一起读书'));A.ok(!e.repo.data.memories.some(m=>m.text==='保留在世界书'));A.equal(Object.keys(books).length,1);
 console.log('UI_PASS existing workshop book preselected -> full entry preview -> selected memory imported; no duplicate book');
 const imported=e.repo.data.memories.find(m=>m.text==='曾一起读书');u.go('memories');click('review-memory-manage');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));[...u.shadow.querySelectorAll('#modals input[name="members"]')].find(n=>n.value===imported.id).checked=true;click('modal-choice','apply');await until(()=>find('modal-choice','yes'));click('modal-choice','yes');await until(()=>!e.repo.data.memories.some(m=>m.id===imported.id));await e.memoryBook.sync({force:true});A.ok(!books['工作簿'].some(r=>r.uid==='manual-a'));A.ok(books['工作簿'].some(r=>r.uid==='manual-b'));A.ok(books['工作簿'].some(r=>r.extra?.tsukiyo.source==='book-studio'));console.log('UI_PASS full memory preview -> bulk deletion -> only linked chosen worldbook entry removed');
 // Real paginated picker must collect checkbox values through modal-choice, not only return choice.
 await e.mutate(s=>{for(let i=0;i<25;i++)w.B.soulEnsure(s.soul,'分页角色'+i);});u.go('soul');click('review-soul-delete');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));const first=u.shadow.querySelector('#modals input[name="members"]');const firstName=first.value;first.checked=true;click('modal-choice','next');await until(()=>u.shadow.querySelector('#modals').textContent.includes('第 2/'));const last=u.shadow.querySelector('#modals input[name="members"]');const lastName=last.value;last.checked=true;click('modal-choice','apply');await until(()=>find('modal-choice','yes'));click('modal-choice','yes');await until(()=>!e.repo.data.soul.roster[firstName]&&!e.repo.data.soul.roster[lastName]);
 console.log('UI_PASS selections survive real page changes');console.log('REVIEW_UI_OK: native DOM buttons, forms and host-stub writes; no real API');
 }finally{app.dispose();dom.window.close();}})().catch(err=>{console.error(err);process.exit(1)});
