const fs=require('fs'),path=require('path'),A=require('node:assert/strict');
let fixture=fs.readFileSync(path.join(__dirname,'test_review.js'),'utf8').split('\n(async()=>{')[0];
fixture=fixture.replace("const names=[","const names=['tpModuleMeta','recycleImport','safetyMemoryPreflight','safetyQueueMemoryDelete','safetyPlan','safetyPreview','safetyPreviewRows','safetyResolve','safetyImportScope','safetyDiagnostics','recycleCapture','recycleRestore','recycleAdd','recycleValidate',");
const {T,engine,uiFor}=new Function('require','__dirname',fixture+';return {T,engine,uiFor};')(require,__dirname);
const clone=x=>JSON.parse(JSON.stringify(x));let count=0;
async function test(name,fn){await fn();count++;console.log('SAFETY_PASS',name);}
(async()=>{
 await test('preview is read-only and calculates exact selected creates',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});e.repo.data.diary.push({id:'b',title:'B',text:'B',ts:2});e.repo.data.contacts[0].bio='手机新简介';const before=clone(e.books);const p=await T.safetyPreview(e.bookStudio);A.equal(p.plan.create.length,1);A.equal(p.plan.update.length,1);A.deepEqual(e.books,before);await e.bookStudio.sync({force:true,selection:{...p,keys:p.plan.create}});A.ok(!e.books['测试书'].find(x=>x.extra.tsukiyo.key==='persona:npc-a').content.includes('手机新简介'));A.ok(e.books['测试书'].some(x=>x.extra.tsukiyo.key==='diary:b'));e.stop();});
 await test('empty scope writes no entries',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});e.repo.data.contacts[0].bio='不执行';const p=await T.safetyPreview(e.bookStudio),before=clone(e.books);await e.bookStudio.sync({force:true,selection:{...p,keys:[]}});A.deepEqual(e.books,before);e.stop();});
 await test('stale local preview rejected',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});const p=await T.safetyPreview(e.bookStudio);e.repo.data.contacts[0].bio='之后修改';await A.rejects(e.bookStudio.sync({force:true,selection:{...p,keys:[]}}),/预览后变化/);e.stop();});
 await test('stale remote preview rejected',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});const p=await T.safetyPreview(e.bookStudio);e.books['测试书'][0].content='之后修改';await A.rejects(e.bookStudio.sync({force:true,selection:{...p,keys:[]}}),/世界书在预览后变化/);e.stop();});
 await test('chat switch rejects selected synchronization',async()=>{const e=engine();await e.bookStudio.link({name:'测试书'});const p=await T.safetyPreview(e.bookStudio);e.now.owner='other';await A.rejects(e.bookStudio.sync({force:true,selection:{...p,keys:[]}}),/变化/);e.stop();});
 async function conflict(){const e=engine();await e.bookStudio.link({name:'测试书'});e.repo.data.contacts[0].bio='本地新';e.books['测试书'].find(x=>x.extra.tsukiyo.key==='persona:npc-a').content='远端新';const p=await T.safetyPreview(e.bookStudio);A.equal(p.plan.conflicts,1);return {e,p};}
 await test('local conflict decision backs up both sides before writing',async()=>{const {e,p}=await conflict();await T.safetyResolve(e.bookStudio,p,'persona:npc-a','local');const backup=e.repo.data.recycle[0];A.equal(backup.kind,'conflict');A.equal(backup.payload.remote.content,'远端新');A.ok(backup.payload.local.content.includes('本地新'));A.ok(e.books['测试书'].find(x=>x.extra.tsukiyo.key==='persona:npc-a').content.includes('本地新'));A.equal((await T.safetyPreview(e.bookStudio)).plan.conflicts,0);e.stop();});
 await test('remote conflict decision keeps persona bio and attaches reference without ping-pong',async()=>{const {e,p}=await conflict();await T.safetyResolve(e.bookStudio,p,'persona:npc-a','remote');A.equal(e.repo.data.contacts[0].bio,'本地新');A.ok(e.repo.data.contacts[0].references.some(x=>x.content==='远端新'));const after=await T.safetyPreview(e.bookStudio);A.equal(after.plan.conflicts,0);A.equal(after.plan.update.length,0);e.stop();});
 await test('manual conflict merge is written and read back consistently',async()=>{const {e,p}=await conflict();await T.safetyResolve(e.bookStudio,p,'persona:npc-a','merge','人工合并');A.ok(e.repo.data.contacts[0].references.some(x=>x.content==='人工合并'));A.equal(e.books['测试书'].find(x=>x.extra.tsukiyo.key==='persona:npc-a').content,'人工合并');A.equal((await T.safetyPreview(e.bookStudio)).plan.conflicts,0);e.stop();});
 await test('stale conflict refuses to overwrite updated remote',async()=>{const {e,p}=await conflict();e.books['测试书'][0].content='更新版本';const before=clone(e.books);await A.rejects(T.safetyResolve(e.bookStudio,p,'persona:npc-a','local'),/已变化/);A.deepEqual(e.books,before);A.ok(!e.repo.data.recycle.length);e.stop();});
 await test('remote write failure keeps conflict backup and local content',async()=>{const {e,p}=await conflict();e.bridge.wbUpdate=async()=>{throw Error('offline')};await A.rejects(T.safetyResolve(e.bookStudio,p,'persona:npc-a','remote'),/offline/);A.equal(e.repo.data.recycle.length,1);A.equal(e.repo.data.contacts[0].bio,'本地新');A.equal(e.bookStudio.running,false);e.stop();});
 await test('recycle captures only deleted whole memories and soul roles',async()=>{const before=T.freshPhone();T.soulEnsure(before.soul,'角色');before.memories=[{id:'m',title:'记忆',text:'保留'}];const after=clone(before);delete after.soul.roster['角色'];after.memories=[];T.recycleCapture(before,after);A.equal(after.recycle.length,2);A.equal(after.recycle[0].payload.text,'保留');});
 await test('restore memory creates local-only ID and cancels queued deletion without remote binding',async()=>{const s=T.freshPhone();s.memoryBook.name='书';s.memoryBook.pendingDelete=[{id:'m',uid:3}];T.recycleAdd(s,'memory','记忆',{id:'m',text:'原文',wb:{uid:3}},'书');const key=s.recycle[0].id;T.recycleRestore(s,[key]);A.notEqual(s.memories[0].id,'m');A.equal(s.memories[0].localOnly,true);A.equal(s.memories[0].wb,undefined);A.equal(s.memoryBook.pendingDelete.length,0);A.equal(s.recycle.length,0);const plan=T.planMemorySync(s.memories,[],{});A.equal(plan.create.length,0);});
 await test('soul restoration is excluded from remote writes and deletion',async()=>{const s=T.freshPhone();T.soulEnsure(s.soul,'角色');const row=clone(s.soul.roster['角色']);delete s.soul.roster['角色'];s.bookSync.managedKeys=['soul:角色'];T.recycleAdd(s,'soul','角色',row);T.recycleRestore(s,[s.recycle[0].id]);A.ok(s.soul.roster['角色']);A.ok(s.bookSync.excludedKeys.includes('soul:角色'));A.ok(!s.bookSync.managedKeys.includes('soul:角色'));});
 await test('restore refuses overwrite of existing same-name soul archive',async()=>{const s=T.freshPhone();T.soulEnsure(s.soul,'角色');T.recycleAdd(s,'soul','角色',s.soul.roster['角色']);A.throws(()=>T.recycleRestore(s,[s.recycle[0].id]),/不会覆盖/);});
 await test('recycle capacity stops new deletion backup instead of evicting old records',async()=>{const s=T.freshPhone();for(let i=0;i<60;i++)T.recycleAdd(s,'memory','m'+i,{id:'m'+i});A.throws(()=>T.recycleAdd(s,'memory','overflow',{id:'overflow'}),/最多60条/);});
 await test('old phone saves normalize with empty recycle',async()=>{const s=T.freshPhone();delete s.recycle;A.deepEqual(T.normalizePhone(s).recycle,[]);});
 await test('scope update remains connected and does not alter remote or existing memory',async()=>{const e=engine();e.books['测试书']=[{uid:'a',name:'a',content:'A'},{uid:'b',name:'b',content:'B'}];await e.memoryBook.link({name:'测试书',acceptExisting:true,importUids:['a']});const entries=await e.bridge.wbRead('测试书'),p={snap:e.now,book:'测试书',inputSig:T.fingerprint([e.repo.data.memoryBook,e.repo.data.memories]),remoteSig:T.fingerprint(entries)},before=clone(e.books);await T.safetyImportScope(e,p,['a','b']);A.deepEqual(e.books,before);A.equal(e.repo.data.memories.length,1);A.equal(e.repo.data.memoryBook.linked,true);await e.memoryBook.sync({force:true});A.equal(e.repo.data.memories.length,2);e.stop();});
 await test('unchecking a range does not delete existing linked memory',async()=>{const e=engine();e.books['测试书']=[{uid:'a',name:'a',content:'A'}];await e.memoryBook.link({name:'测试书',acceptExisting:true,importUids:['a']});const entries=await e.bridge.wbRead('测试书'),p={snap:e.now,book:'测试书',inputSig:T.fingerprint([e.repo.data.memoryBook,e.repo.data.memories]),remoteSig:T.fingerprint(entries)};await T.safetyImportScope(e,p,[]);await e.memoryBook.sync({force:true});A.equal(e.repo.data.memories.length,1);A.equal(e.books['测试书'].length,1);e.stop();});
 await test('scope update rejects stale remote and retains previous range',async()=>{const e=engine();e.books['测试书']=[{uid:'a',name:'a',content:'A'}];await e.memoryBook.link({name:'测试书',acceptExisting:true,importUids:['a']});const entries=await e.bridge.wbRead('测试书'),p={snap:e.now,book:'测试书',inputSig:T.fingerprint([e.repo.data.memoryBook,e.repo.data.memories]),remoteSig:T.fingerprint(entries)};e.books['测试书'][0].content='changed';await A.rejects(T.safetyImportScope(e,p,[]),/已变化/);A.deepEqual(e.repo.data.memoryBook.importUids,['a']);e.stop();});
 await test('diagnostics does not export secrets, book names or message content',async()=>{const e=engine();e.repo.data.memories=[{text:'PRIVATE_TEXT'}];e.settings.data={key:'PRIVATE_KEY',url:'PRIVATE_URL'};e.repo.data.bookSync.name='PRIVATE_BOOK';const report=JSON.stringify(await T.safetyDiagnostics(e));for(const x of ['PRIVATE_TEXT','PRIVATE_KEY','PRIVATE_URL','PRIVATE_BOOK'])A.ok(!report.includes(x));e.stop();});
 await test('recycle exported format imports idempotently without restoring anything',async()=>{const s=T.freshPhone();T.recycleAdd(s,'memory','记忆',{id:'m',text:'原文'});const raw={app:'tsukiyo-phone',kind:'recycle',version:'2.9.5',records:clone(s.recycle)},dest=T.freshPhone();T.recycleImport(dest,raw);T.recycleImport(dest,raw);A.equal(dest.recycle.length,1);A.equal(dest.memories.length,0);A.notEqual(dest.recycle[0].id,s.recycle[0].id);});
 await test('oversized import rejected without touching current recycle',async()=>{const s=T.freshPhone();const raw={app:'tsukiyo-phone',kind:'recycle',records:Array.from({length:61},(_,i)=>({id:'a'+i,kind:'memory',name:'x',at:1,book:'',payload:{id:'m'+i}}))};A.throws(()=>T.recycleImport(s,raw),/最多60条/);A.equal(s.recycle.length,0);});
 await test('legacy pending-deletion IDs normalize to compatible records',async()=>{const s=T.freshPhone();s.memoryBook.pendingDelete=['legacy'];A.deepEqual(T.normalizePhone(s).memoryBook.pendingDelete,[{id:'legacy'}]);});
 await test('full pending deletion queue refuses untracked memory removal',async()=>{const s=T.freshPhone();s.memoryBook.linked=true;s.memoryBook.pendingDelete=Array.from({length:500},(_,i)=>({id:String(i),uid:i}));A.throws(()=>T.safetyQueueMemoryDelete(s,{id:'new',wb:{uid:'new'}}),/队列已满/);A.equal(s.memoryBook.pendingDelete.length,500);});
 await test('full recycle capacity is checked before memory sync writes',async()=>{const s=T.freshPhone();for(let i=0;i<60;i++)T.recycleAdd(s,'memory','a'+i,{id:'a'+i});s.memories=[{id:'m',text:'will disappear'}];A.throws(()=>T.safetyMemoryPreflight(s,{deleteLocal:['m'],guard:''},true),/最多60条/);A.equal(s.recycle.length,60);A.equal(s.memories.length,1);});
 await test('legacy memory clear uses structured queue and leaves summaries intact',async()=>{const s=T.freshPhone();s.memoryBook.linked=true;s.memories=[{id:'m',text:'记忆',wb:{uid:7}}];s.summaries=[{id:'summary',text:'摘要'}];const meta=T.tpModuleMeta({data:s},'memories');A.equal(meta.clear(s),1);A.deepEqual(s.memoryBook.pendingDelete,[{id:'m',uid:7}]);A.equal(s.summaries.length,1);});
 console.log('SAFETY_OK: '+count+' targeted cases (mock host)');
})().catch(e=>{console.error(e);process.exit(1)});
