const fs=require('fs'),path=require('path'),A=require('node:assert/strict'),{JSDOM}=require('jsdom');
let code=fs.readFileSync(path.join(__dirname,'../dist/tsukiyo-phone-v2.9.4.js'),'utf8').replace(/TsukiyoPhoneBundle\.start\([^)]*\);?\s*$/,'');code=code.replace('return __toCommonJS(index_exports);','__export(index_exports,{soulEnsure:()=>soulEnsure});return __toCommonJS(index_exports);');
const dom=new JSDOM('<html><body></body></html>',{runScripts:'outside-only',pretendToBeVisual:true,url:'https://review.test/'}),w=dom.window;w.eval(code+';window.B=TsukiyoPhoneBundle;');const app=w.B.start({mode:'demo',source:w}),delay=ms=>new Promise(r=>setTimeout(r,ms));
async function until(fn){for(let i=0;i<150;i++){if(fn())return;await delay(10);}throw Error('UI timeout: '+app.ui.shadow.getElementById('notices').textContent);}
const find=(act,id,scope)=>[...(scope||app.ui.shadow).querySelectorAll('[data-action]')].find(n=>n.dataset.action===act&&(id===undefined||n.dataset.id===id));
function click(act,id){const el=find(act,id);A.ok(el,'missing button '+act+' '+id);el.click();}
function submit(){const form=app.ui.shadow.querySelector('#modals form');A.ok(form);form.dispatchEvent(new w.Event('submit',{bubbles:true,cancelable:true}));}
function selectOne(value){const boxes=[...app.ui.shadow.querySelectorAll('#modals input[name="members"]')];for(const box of boxes)box.checked=box.value===value;A.ok(boxes.some(x=>x.value===value),'checkbox missing '+value);}
async function confirm(){await until(()=>find('modal-choice','yes'));click('modal-choice','yes');}
(async()=>{try{
 await until(()=>app.engine.state==='ready');const e=app.engine,u=app.ui;e.scheduler.stop();e.arc.stop();e.memoryBook.stop();e.bookStudio.stop();e.soul.stop();e.ms.stop();clearInterval(e.timer);e.memoryBook.stopped=false;e.bookStudio.stopped=false;e.bookStudio.schedule=()=>{};e.memoryBook.schedule=()=>{};
 const books={'工作簿':[]};let next=0;Object.assign(e.bridge,{wbSupported:()=>true,wbWritable:()=>true,wbNames:async()=>Object.keys(books),wbRead:async n=>JSON.parse(JSON.stringify(books[n])),wbBind:async()=>true,wbBindings:async()=>({primary:'工作簿',additional:[],chat:'',global:[]}),wbCreate:async n=>{books[n]=[];return true},wbUpdate:async(n,fn)=>{books[n]=fn(JSON.parse(JSON.stringify(books[n]))).map(r=>({uid:'e'+(++next),...r}));return JSON.parse(JSON.stringify(books[n]));}});
 await e.bookStudio.link({name:'工作簿'});const [a,b]=e.repo.data.contacts.map(c=>c.id),ka='persona:'+a,kb='persona:'+b;
 const oldB=books['工作簿'].find(r=>r.extra.tsukiyo.key===kb).content;
 await e.mutate(s=>{s.contacts[0].bio='选择执行的简介';s.contacts[1].bio='本次不执行的简介';});
 u.open('book');await delay(500);click('safe-sync');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));selectOne(ka);A.ok(u.shadow.querySelector('#modals').textContent.includes('当前世界书'));click('modal-choice','apply');await confirm();await until(()=>books['工作簿'].find(r=>r.extra.tsukiyo.key===ka).content.includes('选择执行的简介'));A.equal(books['工作簿'].find(r=>r.extra.tsukiyo.key===kb).content,oldB);
 console.log('SAFETY_UI_PASS selective sync preview executes only checked entry');
 await until(()=>!e.bookStudio.running);await e.mutate(s=>{s.contacts[0].bio='手机再次修改';});books['工作簿'].find(r=>r.extra.tsukiyo.key===ka).content='远端同时修改';
 u.go('book');click('safe-conflicts');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));selectOne(ka);click('modal-choice','apply');await until(()=>find('modal-choice','merge'));click('modal-choice','merge');await until(()=>u.shadow.querySelector('#modals textarea[name="content"]'));u.shadow.querySelector('#modals textarea[name="content"]').value='人工合并后的资料';submit();await confirm();await until(()=>e.repo.data.contacts[0].references?.some(r=>r.content==='人工合并后的资料'));A.ok(e.repo.data.recycle.some(r=>r.kind==='conflict'));A.equal(books['工作簿'].find(r=>r.extra.tsukiyo.key===ka).content,'人工合并后的资料');
 console.log('SAFETY_UI_PASS conflict merge UI backs up both versions then commits');
 await until(()=>!e.bookStudio.running);await e.mutate(s=>{s.soul.enabled=true;w.B.soulEnsure(s.soul,'回收测试角色');});u.go('soul');click('review-soul-delete');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));selectOne('回收测试角色');click('modal-choice','apply');await confirm();await until(()=>!e.repo.data.soul.roster['回收测试角色']);const archived=e.repo.data.recycle.find(r=>r.kind==='soul');A.ok(archived);
 u.go('soul');click('safe-recycle');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));selectOne(archived.id);click('modal-choice','apply');await until(()=>find('modal-choice','restore'));click('modal-choice','restore');await confirm();await until(()=>e.repo.data.soul.roster['回收测试角色']);A.ok(e.repo.data.bookSync.excludedKeys.includes('soul:回收测试角色'));
 console.log('SAFETY_UI_PASS real role deletion is archived and restored locally without worldbook write');
 books['工作簿'].push({uid:'manual-a',name:'A记忆',content:'A内容'},{uid:'manual-b',name:'B记忆',content:'B内容'});await e.memoryBook.link({name:'工作簿',acceptExisting:true,importUids:['manual-a']});
 u.go('memories');click('safe-import-scope');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));for(const box of u.shadow.querySelectorAll('#modals input[name="members"]'))box.checked=true;click('modal-choice','apply');await until(()=>e.repo.data.memoryBook.importUids.includes('manual-b'));A.equal(e.repo.data.memoryBook.linked,true);A.ok(!e.repo.data.memories.some(m=>m.text==='B内容'));await e.memoryBook.sync({force:true});A.ok(e.repo.data.memories.some(m=>m.text==='B内容'));
 console.log('SAFETY_UI_PASS edit import scope without unlinking; import happens at next sync');
 const target=e.repo.data.memories.find(m=>m.text==='B内容');u.go('memories');click('batch-delete-modal','memories');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));selectOne(target.id);submit();await confirm();await until(()=>!e.repo.data.memories.some(m=>m.id===target.id));A.ok(e.repo.data.memoryBook.pendingDelete.some(r=>r.id===target.id&&r.uid==='manual-b'));const deleted=e.repo.data.recycle.find(r=>r.kind==='memory'&&r.payload.id===target.id);A.ok(deleted);
 u.go('memories');click('safe-recycle');await until(()=>u.shadow.querySelector('#modals input[name="members"]'));selectOne(deleted.id);click('modal-choice','apply');await until(()=>find('modal-choice','restore'));click('modal-choice','restore');await confirm();await until(()=>e.repo.data.memories.some(m=>m.localOnly&&m.text==='B内容'));A.ok(!e.repo.data.memoryBook.pendingDelete.some(r=>r.id===target.id));const restored=e.repo.data.memories.find(m=>m.localOnly);A.notEqual(restored.id,target.id);A.equal(restored.wb,undefined);
 await e.memoryBook.sync({force:true});A.equal(books['工作簿'].filter(r=>r.content==='B内容').length,1);u.go('memories');A.ok(find('safe-memory-publish',restored.id));
 console.log('SAFETY_UI_PASS legacy bulk-delete queue fixed; restore is local-only and cancels pending deletion');
 u.go('settings');click('safe-diagnostics');await until(()=>u.shadow.querySelector('#modals pre'));const diagnostic=u.shadow.querySelector('#modals pre').textContent;const info=JSON.parse(diagnostic);A.equal(info.version,'2.9.4');A.ok(!diagnostic.includes('B内容'));A.ok(!diagnostic.includes('工作簿'));A.equal(info.books.memory.exists,true);click('modal-choice','close');
 console.log('SAFETY_UI_PASS diagnostics screen emits metadata without worldbook names or content');
 const importRecord=JSON.parse(JSON.stringify(archived));u.pickFile=async()=>({text:async()=>JSON.stringify({app:'tsukiyo-phone',kind:'recycle',version:'2.9.4',records:[importRecord]})});
 u.go('settings');click('safe-recycle-import');await confirm();await until(()=>e.repo.data.recycle.some(r=>r.kind==='soul'&&r.name==='回收测试角色'));A.ok(e.repo.data.soul.roster['回收测试角色']);A.equal(e.repo.data.recycle.filter(r=>r.kind==='soul'&&r.name==='回收测试角色').length,1);
 console.log('SAFETY_UI_PASS recycle backup file is imported only into recycle, without overwriting active role');
 await e.mutate(s=>{s.recycle=Array.from({length:60},(_,i)=>({id:'full-'+i,kind:'memory',name:'备份',at:1,book:'',payload:{id:'old-'+i,text:'备份内容'}}));});
 await A.rejects(e.mutate(s=>{delete s.soul.roster['回收测试角色'];}),/最多60条/);A.ok(e.repo.data.soul.roster['回收测试角色']);A.equal(e.repo.data.recycle.length,60);
 console.log('SAFETY_UI_PASS full recycle rejects deletion transaction without losing role');
 console.log('SAFETY_UI_OK: 8 real DOM/repository flows; host/model APIs mocked');
}finally{app.dispose();dom.window.close();}})().catch(err=>{console.error(err);process.exit(1)});
